const germanWords = {
  beginner: [
    // --- A1: Basics ---
    { id: 1, word: "Hallo", translation: "مرحباً" },
    { id: 2, word: "Tschüss", translation: "إلى اللقاء / مع السلامة" },
    { id: 3, word: "Danke", translation: "شكراً" },
    { id: 4, word: "Bitte", translation: "من فضلك / عفواً" },
    { id: 5, word: "Ja", translation: "نعم" },
    { id: 6, word: "Nein", translation: "لا" },
    { id: 7, word: "Ich", translation: "أنا" },
    { id: 8, word: "Du", translation: "أنت (صيغة غير رسمية)" },
    { id: 9, word: "Er", translation: "هو" },
    { id: 10, word: "Sie (singular)", translation: "هي" },
    { id: 11, word: "Wir", translation: "نحن" },
    { id: 12, word: "Ihr", translation: "أنتم (صيغة غير رسمية للجمع)" },
    { id: 13, word: "Sie (plural/formal)", translation: "هم / أنتم (صيغة رسمية)" },
    { id: 14, word: "Sein (Verb)", translation: "يكون" },
    { id: 15, word: "Haben", translation: "يملك / لديه" },
    { id: 16, word: "Kommen", translation: "يأتي" },
    { id: 17, word: "Gehen", translation: "يذهب" },
    { id: 18, word: "Wohnen", translation: "يسكن" },
    { id: 19, word: "Sprechen", translation: "يتحدث" },
    { id: 20, word: "Eins", translation: "واحد" },
    { id: 21, word: "Zwei", translation: "اِثنان" },
    { id: 22, word: "Drei", translation: "ثلاثة" },
    { id: 23, word: "Vier", translation: "أربعة" },
    { id: 24, word: "Fünf", translation: "خمسة" },
    { id: 25, word: "Zehn", translation: "عشرة" },
    { id: 26, word: "Hundert", translation: "مئة" },
    { id: 27, word: "Gestern", translation: "أمس" },
    { id: 28, word: "Heute", translation: "اليوم" },
    { id: 29, word: "Morgen", translation: "غداً" },
    { id: 30, word: "Frühstück", translation: "إفطار" },
    { id: 31, word: "Mittagessen", translation: "غداء" },
    { id: 32, word: "Abendessen", translation: "عشاء" },
    { id: 33, word: "Wasser", translation: "ماء" },
    { id: 34, word: "Brot", translation: "خبز" },
    { id: 35, word: "Kaffee", translation: "قهوة" },
    { id: 36, word: "Tee", translation: "شاي" },
    { id: 37, word: "Geld", translation: "مال" },
    { id: 38, word: "Haus", translation: "منزل" },
    { id: 39, word: "Stadt", translation: "مدينة" },
    { id: 40, word: "Straße", translation: "شارع" },
    { id: 41, word: "Arbeit", translation: "عمل" },
    { id: 42, word: "Schule", translation: "مدرسة" },
    { id: 43, word: "Auto", translation: "سيارة" },
    { id: 44, word: "Zug", translation: "قطار" },
    { id: 45, word: "Flugzeug", translation: "طائرة" },
    { id: 46, word: "Groß", translation: "كبير" },
    { id: 47, word: "Klein", translation: "صغير" },
    { id: 48, word: "Gut", translation: "جيد" },
    { id: 49, word: "Schlecht", translation: "سيئ" },
    { id: 50, word: "Alt", translation: "قديم / كبير في السن" },
    // --- Continuing A1/A2 words (Verbs, Adjectives, Nouns, Prepositions) ---
    { id: 51, word: "Neu", translation: "جديد" },
    { id: 52, word: "Warm", translation: "دافئ" },
    { id: 53, word: "Kalt", translation: "بارد" },
    { id: 54, word: "Müde", translation: "متعب" },
    { id: 55, word: "Hungrig", translation: "جائع" },
    { id: 56, word: "Durstig", translation: "عطشان" },
    { id: 57, word: "Sehen", translation: "يرى" },
    { id: 58, word: "Hören", translation: "يسمع" },
    { id: 59, word: "Lesen", translation: "يقرأ" },
    { id: 60, word: "Schreiben", translation: "يكتب" },
    { id: 61, word: "Essen", translation: "يأكل" },
    { id: 62, word: "Trinken", translation: "يشرب" },
    { id: 63, word: "Machen", translation: "يفعل / يصنع" },
    { id: 64, word: "Kaufen", translation: "يشتري" },
    { id: 65, word: "Verkaufen", translation: "يبيع" },
    { id: 66, word: "Fragen", translation: "يسأل" },
    { id: 67, word: "Antworten", translation: "يجيب" },
    { id: 68, word: "Lernen", translation: "يتعلم" },
    { id: 69, word: "Verstehen", translation: "يفهم" },
    { id: 70, word: "Wissen", translation: "يعرف" },
    { id: 71, word: "Denken", translation: "يفكر" },
    { id: 72, word: "Finden", translation: "يجد" },
    { id: 73, word: "Bleiben", translation: "يبقى" },
    { id: 74, word: "Brauchen", translation: "يحتاج" },
    { id: 75, word: "Geben", translation: "يعطي" },
    { id: 76, word: "Nehmen", translation: "يأخذ" },
    { id: 77, word: "Zeigen", translation: "يُظهر / يُشير" },
    { id: 78, word: "Suchen", translation: "يبحث" },
    { id: 79, word: "Anrufen", translation: "يتصل هاتفياً" },
    { id: 80, word: "Warten", translation: "ينتظر" },
    { id: 81, word: "Zimmer", translation: "غرفة" },
    { id: 82, word: "Tisch", translation: "طاولة" },
    { id: 83, word: "Stuhl", translation: "كرسي" },
    { id: 84, word: "Fenster", translation: "نافذة" },
    { id: 85, word: "Tür", translation: "باب" },
    { id: 86, word: "Licht", translation: "ضوء" },
    { id: 87, word: "Telefon", translation: "هاتف" },
    { id: 88, word: "Computer", translation: "حاسوب" },
    { id: 89, word: "Buch", translation: "كتاب" },
    { id: 90, word: "Blatt", translation: "ورقة" },
    { id: 91, word: "Uhr", translation: "ساعة" },
    { id: 92, word: "Tag", translation: "يوم" },
    { id: 93, word: "Woche", translation: "أسبوع" },
    { id: 94, word: "Monat", translation: "شهر" },
    { id: 95, word: "Jahr", translation: "سنة" },
    { id: 96, word: "Familie", translation: "عائلة" },
    { id: 97, word: "Eltern", translation: "الوالدان" },
    { id: 98, word: "Kind", translation: "طفل" },
    { id: 99, word: "Mann", translation: "رجل" },
    { id: 100, word: "Frau", translation: "اِمرأة" },
    // --- A2: Expanding Vocabulary and Grammar ---
    { id: 101, word: "Freund", translation: "صديق" },
    { id: 102, word: "Kollege", translation: "زميل عمل" },
    { id: 103, word: "Führerschein", translation: "رخصة قيادة" },
    { id: 104, word: "Geschenk", translation: "هدية" },
    { id: 105, word: "Geburtstag", translation: "عيد ميلاد" },
    { id: 106, word: "Ferien", translation: "إجازة / عطلة" },
    { id: 107, word: "Termin", translation: "موعد" },
    { id: 108, word: "Rechnung", translation: "فاتورة" },
    { id: 109, word: "Supermarkt", translation: "سوبر ماركت" },
    { id: 110, word: "Apotheke", translation: "صيدلية" },
    { id: 111, word: "Bank", translation: "بنك" },
    { id: 112, word: "Bahnhof", translation: "محطة قطار" },
    { id: 113, word: "Flughafen", translation: "مطار" },
    { id: 114, word: "Fahrkarte", translation: "تذكرة سفر" },
    { id: 115, word: "Problem", translation: "مشكلة" },
    { id: 116, word: "Lösung", translation: "حل" },
    { id: 117, word: "Wichtig", translation: "مهم" },
    { id: 118, word: "Einfach", translation: "سهل / بسيط" },
    { id: 119, word: "Schwer", translation: "صعب / ثقيل" },
    { id: 120, word: "Schnell", translation: "سريع" },
    { id: 121, word: "Langsam", translation: "بطيء" },
    { id: 122, word: "Glücklich", translation: "سعيد" },
    { id: 123, word: "Traurig", translation: "حزين" },
    { id: 124, word: "Ärgerlich", translation: "غاضب / منزعج" },
    { id: 125, word: "Gesund", translation: "صحي" },
    { id: 126, word: "Krank", translation: "مريض" },
    { id: 127, word: "Mögen", translation: "يحب / يرغب" },
    { id: 128, word: "Wollen", translation: "يريد" },
    { id: 129, word: "Müssen", translation: "يجب (اِلتزام داخلي)" },
    { id: 130, word: "Sollen", translation: "ينبغي (نصيحة أو اِلتزام خارجي)" },
    { id: 131, word: "Können", translation: "يستطيع" },
    { id: 132, word: "Dürfen", translation: "يُسمح له" },
    { id: 133, word: "Fahren", translation: "يسافر / يقود" },
    { id: 134, word: "Anziehen", translation: "يرتدي / يلبس" },
    { id: 135, word: "Ausziehen", translation: "يخلع" },
    { id: 136, word: "Einkaufen", translation: "يتسوق" },
    { id: 137, word: "Aufstehen", translation: "يستيقظ / يقف" },
    { id: 138, word: "Zurückkommen", translation: "يعود / يرجع" },
    { id: 139, word: "Bezahlen", translation: "يدفع" },
    { id: 140, word: "Buchen", translation: "يحجز" },
    { id: 141, word: "Passieren", translation: "يحدث" },
    { id: 142, word: "Verlieren", translation: "يخسر / يضيع" },
    { id: 143, word: "Finden", translation: "يجد" },
    { id: 144, word: "Öffnen", translation: "يفتح" },
    { id: 145, word: "Schließen", translation: "يُغلق" },
    { id: 146, word: "Beginnen", translation: "يبدأ" },
    { id: 147, word: "Enden", translation: "ينهي" },
    { id: 148, word: "Versuchen", translation: "يحاول" },
    { id: 149, word: "Wiederholen", translation: "يكرر" },
    { id: 150, word: "Erklären", translation: "يشرح" },
    // --- Filling out the A1/A2 list (common Nouns/Prepositions/Adjectives) ---
    { id: 151, word: "Dort", translation: "هناك" },
    { id: 152, word: "Hier", translation: "هنا" },
    { id: 153, word: "Oben", translation: "أعلى" },
    { id: 154, word: "Unten", translation: "أسفل" },
    { id: 155, word: "Links", translation: "يسار" },
    { id: 156, word: "Rechts", translation: "يمين" },
    { id: 157, word: "Geradeaus", translation: "مستقيم" },
    { id: 158, word: "Vor", translation: "أمام / قبل" },
    { id: 159, word: "Hinter", translation: "خلف" },
    { id: 160, word: "Neben", translation: "بجانب" },
    { id: 161, word: "Auf", translation: "على (أفقي)" },
    { id: 162, word: "Unter", translation: "تحت" },
    { id: 163, word: "In", translation: "في / داخل" },
    { id: 164, word: "Zwischen", translation: "بين" },
    { id: 165, word: "An", translation: "على (عمودي)" },
    { id: 166, word: "Bei", translation: "عند / لدى" },
    { id: 167, word: "Mit", translation: "مع" },
    { id: 168, word: "Von", translation: "من / عن" },
    { id: 169, word: "Nach", translation: "إلى / بعد" },
    { id: 170, word: "Zu", translation: "إلى (شخص أو مكان)" },
    { id: 171, word: "Ohne", translation: "بدون" },
    { id: 172, word: "Gegen", translation: "ضد" },
    { id: 173, word: "Durch", translation: "من خلال" },
    { id: 174, word: "Für", translation: "لأجل / من أجل" },
    { id: 175, word: "Um", translation: "حول / في حوالي" },
    { id: 176, word: "Seit", translation: "منذ" },
    { id: 177, word: "Während", translation: "خلال" },
    { id: 178, word: "Wegen", translation: "بسبب" },
    { id: 179, word: "Obwohl", translation: "على الرغم من" },
    { id: 180, word: "Weil", translation: "لأن" },
    { id: 181, word: "Dass", translation: "أنّ" },
    { id: 182, word: "Wenn", translation: "إذا / عندما" },
    { id: 183, word: "Sondern", translation: "بل (للنفي)" },
    { id: 184, word: "Aber", translation: "لكن" },
    { id: 185, word: "Oder", translation: "أو" },
    { id: 186, word: "Und", translation: "و" },
    { id: 187, word: "Denn", translation: "لأن (قبل الفعل)" },
    { id: 188, word: "Etwas", translation: "شيء ما" },
    { id: 189, word: "Nichts", translation: "لا شيء" },
    { id: 190, word: "Jemand", translation: "شخص ما" },
    { id: 191, word: "Niemand", translation: "لا أحد" },
    { id: 192, word: "Jeder", translation: "كل شخص" },
    { id: 193, word: "Manchmal", translation: "أحياناً" },
    { id: 194, word: "Oft", translation: "غالباً" },
    { id: 195, word: "Immer", translation: "دائماً" },
    { id: 196, word: "Nie", translation: "أبداً" },
    { id: 197, word: "Viel", translation: "كثير" },
    { id: 198, word: "Wenig", translation: "قليل" },
    { id: 199, word: "Gern", translation: "بسرور / بحب" },
    { id: 200, word: "Leider", translation: "للأسف" },
    { id: 201, word: "Richtig", translation: "صحيح" },
    { id: 202, word: "Falsch", translation: "خاطئ" },
    { id: 203, word: "Helfen", translation: "يساعد" },
    { id: 204, word: "Beginn", translation: "بداية" },
    { id: 205, word: "Ende", translation: "نهاية" },
    { id: 206, word: "Büro", translation: "مكتب" },
    { id: 207, word: "Zeitung", translation: "جريدة" },
    { id: 208, word: "Brief", translation: "رسالة" },
    { id: 209, word: "Post", translation: "بريد" },
    { id: 210, word: "Paket", translation: "طرد" },
    { id: 211, word: "Adresse", translation: "عنوان" },
    { id: 212, word: "Pass", translation: "جواز سفر" },
    { id: 213, word: "Visum", translation: "تأشيرة" },
    { id: 214, word: "Krankenhaus", translation: "مستشفى" },
    { id: 215, word: "Notarzt", translation: "طبيب طوارئ" },
    { id: 216, word: "Feuerwehr", translation: "إطفائية" },
    { id: 217, word: "Polizei", translation: "شرطة" },
    { id: 218, word: "Unfall", translation: "حادث" },
    { id: 219, word: "Schmerzen", translation: "آلام" },
    { id: 220, word: "Medikament", translation: "دواء" },
    { id: 221, word: "Temperatur", translation: "درجة الحرارة" },
    { id: 222, word: "Fieber", translation: "حمى" },
    { id: 223, word: "Husten", translation: "سعال" },
    { id: 224, word: "Schnupfen", translation: "زكام" },
    { id: 225, word: "Arzt", translation: "طبيب" },
    { id: 226, word: "Patient", translation: "مريض (شخص)" },
    { id: 227, word: "Pflege", translation: "رعاية" },
    { id: 228, word: "Beruf", translation: "مهنة" },
    { id: 229, word: "Studium", translation: "دراسة جامعية" },
    { id: 230, word: "Ausbildung", translation: "تدريب مهني" },
    { id: 231, word: "Gehalt", translation: "راتب" },
    { id: 232, word: "Chef", translation: "رئيس عمل" },
    { id: 233, word: "Bewerbung", translation: "طلب عمل" },
    { id: 234, word: "Lebenslauf", translation: "سيرة ذاتية" },
    { id: 235, word: "Gespräch", translation: "محادثة / مقابلة" },
    { id: 236, word: "Pause", translation: "اِستراحة" },
    { id: 237, word: "Feierabend", translation: "نهاية يوم العمل" },
    { id: 238, word: "Geldautomat", translation: "صراف آلي" },
    { id: 239, word: "Konto", translation: "حساب (بنكي)" },
    { id: 240, word: "Überweisung", translation: "تحويل مالي" },
    { id: 241, word: "Sparen", translation: "يدخر" },
    { id: 242, word: "Ausgeben", translation: "يُنفق" },
    { id: 243, word: "Miete", translation: "إيجار" },
    { id: 244, word: "Nebenkosten", translation: "تكاليف اِضافية" },
    { id: 245, word: "Strom", translation: "كهرباء" },
    { id: 246, word: "Heizung", translation: "تدفئة" },
    { id: 247, word: "Umzug", translation: "اِنتقال (منزل)" },
    { id: 248, word: "Kündigen", translation: "يُنهي / يلغي" },
    { id: 249, word: "Vertrag", translation: "عقد" },
    { id: 250, word: "Unterschrift", translation: "توقيع" },
    { id: 251, word: "Warten", translation: "ينتظر" },
    { id: 252, word: "Zahlen", translation: "يدفع / يحسب" },
    { id: 253, word: "Abholen", translation: "يستلم / يأخذ" },
    { id: 254, word: "Anbieten", translation: "يقدم / يعرض" },
    { id: 255, word: "Erlauben", translation: "يسمح" },
    { id: 256, word: "Verboten", translation: "ممنوع" },
    { id: 257, word: "Verspätung", translation: "تأخير" },
    { id: 258, word: "Pünktlich", translation: "في الموعد تماماً" },
    { id: 259, word: "Verabredung", translation: "موعد / لقاء" },
    { id: 260, word: "Weg", translation: "طريق" },
    { id: 261, word: "Karte", translation: "خريطة / بطاقة" },
    { id: 262, word: "Rucksack", translation: "حقيبة ظهر" },
    { id: 263, word: "Gepäck", translation: "أمتعة" },
    { id: 264, word: "Grenze", translation: "حدود" },
    { id: 265, word: "Zoll", translation: "جمارك" },
    { id: 266, word: "Tourist", translation: "سائح" },
    { id: 267, word: "Sehenswürdigkeit", translation: "مكان سياحي" },
    { id: 268, word: "Museum", translation: "متحف" },
    { id: 269, word: "Kirche", translation: "كنيسة" },
    { id: 270, word: "Moschee", translation: "مسجد" },
    { id: 271, word: "Markt", translation: "سوق" },
    { id: 272, word: "Bäcker", translation: "خباز" },
    { id: 273, word: "Metzger", translation: "جزار" },
    { id: 274, word: "Obst", translation: "فواكه" },
    { id: 275, word: "Gemüse", translation: "خضروات" },
    { id: 276, word: "Fleisch", translation: "لحم" },
    { id: 277, word: "Käse", translation: "جبن" },
    { id: 278, word: "Milch", translation: "حليب" },
    { id: 279, word: "Zucker", translation: "سكر" },
    { id: 280, word: "Salz", translation: "ملح" },
    { id: 281, word: "Scharf", translation: "حار / حاد" },
    { id: 282, word: "Süß", translation: "حلو" },
    { id: 283, word: "Sauer", translation: "حامض" },
    { id: 284, word: "Bitter", translation: "مر" },
    { id: 285, word: "Geschmack", translation: "طعم / ذوق" },
    { id: 286, word: "Duft", translation: "رائحة / عطر" },
    { id: 287, word: "Geräusch", translation: "ضوضاء / صوت" },
    { id: 288, word: "Musik", translation: "موسيقى" },
    { id: 289, word: "Film", translation: "فيلم" },
    { id: 290, word: "Theater", translation: "مسرح" },
    { id: 291, word: "Sport", translation: "رياضة" },
    { id: 292, word: "Fußball", translation: "كرة قدم" },
    { id: 293, word: "Schwimmen", translation: "سباحة" },
    { id: 294, word: "Tanzen", translation: "يرقص" },
    { id: 295, word: "Laufen", translation: "يركض / يمشي" },
    { id: 296, word: "Sitzen", translation: "يجلس" },
    { id: 297, word: "Stehen", translation: "يقف" },
    { id: 298, word: "Liegen", translation: "يستلقي" },
    { id: 299, word: "Schlafen", translation: "ينام" },
    { id: 300, word: "Aufwachen", translation: "يستيقظ" },
    { id: 301, word: "Dusche", translation: "دش / اِستحمام" },
    { id: 302, word: "Zähne putzen", translation: "يفرش أسنانه" },
    { id: 303, word: "Anziehen", translation: "يرتدي" },
    { id: 304, word: "Frisur", translation: "تسريحة شعر" },
    { id: 305, word: "Spiegel", translation: "مرآة" },
    { id: 306, word: "Kamm", translation: "مِشط" },
    { id: 307, word: "Seife", translation: "صابون" },
    { id: 308, word: "Handtuch", translation: "منشفة" },
    { id: 309, word: "Wäsche", translation: "غسيل" },
    { id: 310, word: "Bügeln", translation: "يكوي" },
    { id: 311, word: "Reinigen", translation: "ينظف" },
    { id: 312, word: "Ordnung", translation: "نظام / ترتيب" },
    { id: 313, word: "Chaos", translation: "فوضى" },
    { id: 314, word: "Besuch", translation: "زيارة" },
    { id: 315, word: "Einladen", translation: "يدعو" },
    { id: 316, word: "Klingeln", translation: "يرن الجرس" },
    { id: 317, word: "Nachbar", translation: "جار" },
    { id: 318, word: "Hilfe", translation: "مساعدة" },
    { id: 319, word: "Wetter", translation: "طقس" },
    { id: 320, word: "Regen", translation: "مطر" },
    { id: 321, word: "Schnee", translation: "ثلج" },
    { id: 322, word: "Sonne", translation: "شمس" },
    { id: 323, word: "Wolke", translation: "سحابة" },
    { id: 324, word: "Wind", translation: "ريح" },
    { id: 325, word: "Blitz", translation: "برق" },
    { id: 326, word: "Donner", translation: "رعد" },
    { id: 327, word: "Gewitter", translation: "عاصفة رعدية" },
    { id: 328, word: "Nass", translation: "مبلل" },
    { id: 329, word: "Trocken", translation: "جاف" },
    { id: 330, word: "Hell", translation: "مضيء / فاتح" },
    { id: 331, word: "Dunkel", translation: "مظلم / داكن" },
    { id: 332, word: "Eng", translation: "ضيق" },
    { id: 333, word: "Weit", translation: "واسع / بعيد" },
    { id: 334, word: "Kurz", translation: "قصير" },
    { id: 335, word: "Lang", translation: "طويل" },
    { id: 336, word: "Hoch", translation: "عالٍ" },
    { id: 337, word: "Niedrig", translation: "منخفض" },
    { id: 338, word: "Dick", translation: "سميك / بدين" },
    { id: 339, word: "Dünn", translation: "نحيف / رقيق" },
    { id: 340, word: "Sauber", translation: "نظيف" },
    { id: 341, word: "Schmutzig", translation: "متسخ" },
    { id: 342, word: "Leise", translation: "هادئ" },
    { id: 343, word: "Laut", translation: "صاخب" },
    { id: 344, word: "Frei", translation: "حُر" },
    { id: 345, word: "Besetzt", translation: "مشغول / محجوز" },
    { id: 346, word: "Rauchen", translation: "يدخن" },
    { id: 347, word: "Erlaubnis", translation: "إذن / سماح" },
    { id: 348, word: "Pflicht", translation: "واجب / اِلتزام" },
    { id: 349, word: "Regel", translation: "قاعدة" },
    { id: 350, word: "Strafe", translation: "عقوبة" },
    { id: 351, word: "Vorschlag", translation: "اِقتراح" },
    { id: 352, word: "Zustimmen", translation: "يوافق" },
    { id: 353, word: "Ablehnen", translation: "يرفض" },
    { id: 354, word: "Entscheiden", translation: "يقرر" },
    { id: 355, word: "Meinen", translation: "يعني / يقصد" },
    { id: 356, word: "Glauben", translation: "يعتقد / يؤمن" },
    { id: 357, word: "Hoffen", translation: "يأمل" },
    { id: 358, word: "Wünschen", translation: "يتمنى" },
    { id: 359, word: "Glück", translation: "حظ / سعادة" },
    { id: 360, word: "Pech", translation: "سوء حظ" },
    { id: 361, word: "Spaß", translation: "متعة / مرح" },
    { id: 362, word: "Traum", translation: "حلم" },
    { id: 363, word: "Albtraum", translation: "كابوس" },
    { id: 364, word: "Herz", translation: "قلب" },
    { id: 365, word: "Kopf", translation: "رأس" },
    { id: 366, word: "Hand", translation: "يد" },
    { id: 367, word: "Fuß", translation: "قدم" },
    { id: 368, word: "Auge", translation: "عين" },
    { id: 369, word: "Ohr", translation: "أذن" },
    { id: 370, word: "Nase", translation: "أنف" },
    { id: 371, word: "Mund", translation: "فم" },
    { id: 372, word: "Zahn", translation: "سن" },
    { id: 373, word: "Haar", translation: "شعر" },
    { id: 374, word: "Haut", translation: "جلد" },
    { id: 375, word: "Bauch", translation: "بطن" },
    { id: 376, word: "Rücken", translation: "ظهر" },
    { id: 377, word: "Arm", translation: "ذراع" },
    { id: 378, word: "Bein", translation: "ساق" },
    { id: 379, word: "Finger", translation: "اِصبع" },
    { id: 380, word: "Körper", translation: "جسم" },
    { id: 381, word: "Erkältung", translation: "نزلة برد" },
    { id: 382, word: "Halsweh", translation: "اِلتهاب الحلق" },
    { id: 383, word: "Zahnschmerzen", translation: "ألم اِلأسنان" },
    { id: 384, word: "Kopfschmerzen", translation: "صداع" },
    { id: 385, word: "Atem", translation: "نَفَس" },
    { id: 386, word: "Lunge", translation: "رئة" },
    { id: 387, word: "Blut", translation: "دم" },
    { id: 388, word: "Gefühl", translation: "شعور" },
    { id: 389, word: "Liebe", translation: "حب" },
    { id: 390, word: "Hass", translation: "كراهية" },
    { id: 391, word: "Angst", translation: "خوف" },
    { id: 392, word: "Mut", translation: "شجاعة" },
    { id: 393, word: "Trauer", translation: "حزن" },
    { id: 394, word: "Freude", translation: "فرح" },
    { id: 395, word: "Wut", translation: "غضب" },
    { id: 396, word: "Überraschung", translation: "مفاجأة" },
    { id: 397, word: "Peinlich", translation: "مُحرج" },
    { id: 398, word: "Interessant", translation: "مثير للاِهتمام" },
    { id: 399, word: "Langweilig", translation: "ممل" },
    { id: 400, word: "Spannend", translation: "مشوق" },
    { id: 401, word: "Nützlich", translation: "مفيد" },
    { id: 402, word: "Schädlich", translation: "ضار" },
    { id: 403, word: "Gefährlich", translation: "خطير" },
    { id: 404, word: "Sicher", translation: "آمن" },
    { id: 405, word: "Ehrlich", translation: "صادق" },
    { id: 406, word: "Lügen", translation: "يكذب" },
    { id: 407, word: "Geheimnis", translation: "سر" },
    { id: 408, word: "Lärm", translation: "ضجيج" },
    { id: 409, word: "Stille", translation: "صمت" },
    { id: 410, word: "Ruhe", translation: "هدوء" },
    { id: 411, word: "Eile", translation: "عجلة / اِستعجال" },
    { id: 412, word: "Geduld", translation: "صبر" },
    { id: 413, word: "Ungeduld", translation: "نفاذ الصبر" },
    { id: 414, word: "Möglich", translation: "ممكن" },
    { id: 415, word: "Unmöglich", translation: "مستحيل" },
    { id: 416, word: "Nötig", translation: "ضروري" },
    { id: 417, word: "Überflüssig", translation: "زائد عن الحاجة" },
    { id: 418, word: "Echt", translation: "حقيقي / أصلي" },
    { id: 419, word: "Falsch", translation: "مزيف / خطأ" },
    { id: 420, word: "Besonders", translation: "خاص / بشكل خاص" },
    { id: 421, word: "Normal", translation: "عادي" },
    { id: 422, word: "Selten", translation: "نادر" },
    { id: 423, word: "Häufig", translation: "متكرر" },
    { id: 424, word: "Plötzlich", translation: "فجأة" },
    { id: 425, word: "Schließlich", translation: "في النهاية" },
    { id: 426, word: "Zuerst", translation: "أولاً" },
    { id: 427, word: "Danach", translation: "بعد ذلك" },
    { id: 428, word: "Trotzdem", translation: "بالرغم من ذلك" },
    { id: 429, word: "Deshalb", translation: "لذلك" },
    { id: 430, word: "Außerdem", translation: "علاوة على ذلك" },
    { id: 431, word: "Sogar", translation: "حتى / بالرغم من" },
    { id: 432, word: "Meistens", translation: "في معظم الأوقات" },
    { id: 433, word: "Vielleicht", translation: "ربما" },
    { id: 434, word: "Bestimmt", translation: "بالتأكيد" },
    { id: 435, word: "Wirklich", translation: "حقا" },
    { id: 436, word: "Fast", translation: "تقريباً" },
    { id: 437, word: "Genug", translation: "كافٍ" },
    { id: 438, word: "Zu viel", translation: "أكثر من اللازم" },
    { id: 439, word: "Alle", translation: "جميع" },
    { id: 440, word: "Keiner", translation: "لا أحد / لا شيء" },
    { id: 441, word: "Beide", translation: "كلاهما" },
    { id: 442, word: "Man", translation: "المرء / الناس" },
    { id: 443, word: "Oftmals", translation: "في كثير من الأحيان" },
    { id: 444, word: "Zusammen", translation: "معاً" },
    { id: 445, word: "Allein", translation: "بمفرده" },
    { id: 446, word: "Einig", translation: "متفق" },
    { id: 447, word: "Streiten", translation: "يتشاجر / يتنازع" },
    { id: 448, word: "Lachen", translation: "يضحك" },
    { id: 449, word: "Weinen", translation: "يبكي" },
    { id: 450, word: "Kochen", translation: "يطبخ" },
    { id: 451, word: "Spülen", translation: "يغسل الصحون" },
    { id: 452, word: "Aufräumen", translation: "يرتب" },
    { id: 453, word: "Wischen", translation: "يمسح / يكنس" },
    { id: 454, word: "Kühlen", translation: "يُبرّد" },
    { id: 455, word: "Heizen", translation: "يدفئ" },
    { id: 456, word: "Garten", translation: "حديقة" },
    { id: 457, word: "Blume", translation: "زهرة" },
    { id: 458, word: "Baum", translation: "شجرة" },
    { id: 459, word: "Tier", translation: "حيوان" },
    { id: 460, word: "Vogel", translation: "طائر" },
    { id: 461, word: "Fisch", translation: "سمكة" },
    { id: 462, word: "Hund", translation: "كلب" },
    { id: 463, word: "Katze", translation: "قطة" },
    { id: 464, word: "Maus", translation: "فأر" },
    { id: 465, word: "Insekt", translation: "حشرة" },
    { id: 466, word: "Natur", translation: "طبيعة" },
    { id: 467, word: "Umwelt", translation: "بيئة" },
    { id: 468, word: "Luft", translation: "هواء" },
    { id: 469, word: "Erde", translation: "أرض" },
    { id: 470, word: "Sonne", translation: "شمس" },
    { id: 471, word: "Mond", translation: "قمر" },
    { id: 472, word: "Stern", translation: "نجم" },
    { id: 473, word: "Himmel", translation: "سماء" },
    { id: 474, word: "Meer", translation: "بحر" },
    { id: 475, word: "Fluss", translation: "نهر" },
    { id: 476, word: "Berg", translation: "جبل" },
    { id: 477, word: "Feld", translation: "حقل" },
    { id: 478, word: "Wald", translation: "غابة" },
    { id: 479, word: "Osten", translation: "شرق" },
    { id: 480, word: "Westen", translation: "غرب" },
    { id: 481, word: "Norden", translation: "شمال" },
    { id: 482, word: "Süden", translation: "جنوب" },
    { id: 483, word: "Richtung", translation: "اِتجاه" },
    { id: 484, word: "Abbiegen", translation: "يستدير" },
    { id: 485, word: "Überqueren", translation: "يعبر" },
    { id: 486, word: "Zurück", translation: "خلف / إلى الوراء" },
    { id: 487, word: "Vorbei", translation: "ماراً بـ" },
    { id: 488, word: "Gegenüber", translation: "مقابل" },
    { id: 489, word: "Erreichen", translation: "يصل إلى" },
    { id: 490, word: "Brauchen", translation: "يحتاج" },
    { id: 491, word: "Dauer", translation: "مدة" },
    { id: 492, word: "Viertel", translation: "ربع" },
    { id: 493, word: "Halb", translation: "نصف" },
    { id: 494, word: "Ganze", translation: "كامل" },
    { id: 495, word: "Teil", translation: "جزء" },
    { id: 496, word: "Mehr", translation: "أكثر" },
    { id: 497, word: "Weniger", translation: "أقل" },
    { id: 498, word: "Erstens", translation: "أولاً" },
    { id: 499, word: "Zweitens", translation: "ثانياً" },
    { id: 500, word: "Letztens", translation: "أخيراً" }
  ],
  intermediate: [
    // --- B1: Intermediate Competence ---
    { id: 501, word: "Beziehung", translation: "علاقة / اِرتباط" },
    { id: 502, word: "Verantwortung", translation: "مسؤولية" },
    { id: 503, word: "Entscheidung", translation: "قرار" },
    { id: 504, word: "Herausforderung", translation: "تحدّي" },
    { id: 505, word: "Möglichkeit", translation: "اِحتمال / إمكانية" },
    { id: 506, word: "Gelegenheit", translation: "فرصة" },
    { id: 507, word: "Gesellschaft", translation: "مجتمع" },
    { id: 508, word: "Politik", translation: "سياسة" },
    { id: 509, word: "Wirtschaft", translation: "اِقتصاد" },
    { id: 510, word: "Umweltschutz", translation: "حماية البيئة" },
    { id: 511, word: "Bildung", translation: "تعليم" },
    { id: 512, word: "Forschung", translation: "بحث علمي" },
    { id: 513, word: "Technologie", translation: "تكنولوجيا" },
    { id: 514, word: "Kultur", translation: "ثقافة" },
    { id: 515, word: "Geschichte", translation: "تاريخ / قصة" },
    { id: 516, word: "Zukunft", translation: "مستقبل" },
    { id: 517, word: "Vergangenheit", translation: "ماضي" },
    { id: 518, word: "Gegenwart", translation: "حاضر" },
    { id: 519, word: "Auswirkung", translation: "تأثير / اِنعكاس" },
    { id: 520, word: "Ziel", translation: "هدف" },
    { id: 521, word: "Erfolg", translation: "نجاح" },
    { id: 522, word: "Misserfolg", translation: "فشل" },
    { id: 523, word: "Leistung", translation: "إنجاز / أداء" },
    { id: 524, word: "Bedeutung", translation: "معنى / أهمية" },
    { id: 525, word: "Vertrauen", translation: "ثقة" },
    { id: 526, word: "Zweifel", translation: "شك" },
    { id: 527, word: "Kritik", translation: "نقد" },
    { id: 528, word: "Meinung", translation: "رأي" },
    { id: 529, word: "Standpunkt", translation: "وجهة نظر" },
    { id: 530, word: "Argument", translation: "حجة" },
    { id: 531, word: "Vorteil", translation: "ميزة" },
    { id: 532, word: "Nachteil", translation: "عيب" },
    { id: 533, word: "Vergleich", translation: "مقارنة" },
    { id: 534, word: "Ursache", translation: "سبب" },
    { id: 535, word: "Folge", translation: "نتيجة" },
    { id: 536, word: "Behaupten", translation: "يدّعي" },
    { id: 537, word: "Überzeugen", translation: "يُقنع" },
    { id: 538, word: "Diskutieren", translation: "يناقش" },
    { id: 539, word: "Erläutern", translation: "يشرح / يوضح" },
    { id: 540, word: "Begründen", translation: "يبرر / يسوغ" },
    { id: 541, word: "Vermuten", translation: "يخمّن / يفترض" },
    { id: 542, word: "Bestätigen", translation: "يؤكد" },
    { id: 543, word: "Widersprechen", translation: "يُعارض" },
    { id: 544, word: "Ableiten", translation: "يستنتج / يشتق" },
    { id: 545, word: "Entwickeln", translation: "يطور" },
    { id: 546, word: "Gründen", translation: "يؤسس" },
    { id: 547, word: "Betreiben", translation: "يُدير / يُشغّل" },
    { id: 548, word: "Erhalten", translation: "يحصل على / يحافظ على" },
    { id: 549, word: "Schaffen", translation: "يخلق / ينجز" },
    { id: 550, word: "Handeln", translation: "يتصرف / يتاجر" },
    { id: 551, word: "Beziehen", translation: "يشير إلى / يتعلق بـ" },
    { id: 552, word: "Erfordern", translation: "يتطلب" },
    { id: 553, word: "Gelten", translation: "يسري / يُعتبر" },
    { id: 554, word: "Leiden", translation: "يعاني" },
    { id: 555, word: "Erkennen", translation: "يتعرف على / يدرك" },
    { id: 556, word: "Annehmen", translation: "يفترض / يقبل" },
    { id: 557, word: "Erleben", translation: "يعيش / يختبر" },
    { id: 558, word: "Auseinandersetzen", translation: "يتناول (موضوعاً) / يتجادل" },
    { id: 559, word: "Durchführen", translation: "ينفذ" },
    { id: 560, word: "Gestalten", translation: "يُشكّل / يُصمم" },
    { id: 561, word: "Unvermeidbar", translation: "لا مفر منه" },
    { id: 562, word: "Erheblich", translation: "كبير / هام" },
    { id: 563, word: "Angemessen", translation: "مناسب / معقول" },
    { id: 564, word: "Umfassend", translation: "شامل" },
    { id: 565, word: "Komplex", translation: "معقد" },
    { id: 566, word: "Fraglich", translation: "مشكوك فيه" },
    { id: 567, word: "Zuverlässig", translation: "موثوق به" },
    { id: 568, word: "Unabhängig", translation: "مستقل" },
    { id: 569, word: "Gegenseitig", translation: "متبادل" },
    { id: 570, word: "Nachhaltig", translation: "مستدام" },
    { id: 571, word: "Zunehmend", translation: "متزايد" },
    { id: 572, word: "Eindeutig", translation: "واضح / قطعي" },
    { id: 573, word: "Geheim", translation: "سري" },
    { id: 574, word: "Öffentlich", translation: "عام / علني" },
    { id: 575, word: "Privat", translation: "خاص" },
    { id: 576, word: "Sozial", translation: "اِجتماعي" },
    { id: 577, word: "Religiös", translation: "ديني" },
    { id: 578, word: "Kulturell", translation: "ثقافي" },
    { id: 579, word: "Historisch", translation: "تاريخي" },
    { id: 580, word: "Wissenschaftlich", translation: "علمي" },
    { id: 581, word: "Aktuell", translation: "حالي / راهن" },
    { id: 582, word: "Vorherig", translation: "سابق" },
    { id: 583, word: "Zukünftig", translation: "مستقبلي" },
    { id: 584, word: "Innerhalb", translation: "داخل / ضمن" },
    { id: 585, word: "Außerhalb", translation: "خارج" },
    { id: 586, word: "Trotz", translation: "على الرغم من" },
    { id: 587, word: "Aufgrund", translation: "بسبب" },
    { id: 588, word: "Wegen", translation: "بسبب" },
    { id: 589, word: "Während", translation: "خلال" },
    { id: 590, word: "Bezüglich", translation: "بخصوص" },
    { id: 591, word: "Sowohl ... als auch", translation: "كلا من ... و" },
    { id: 592, word: "Entweder ... oder", translation: "إما ... أو" },
    { id: 593, word: "Weder ... noch", translation: "لا ... ولا" },
    { id: 594, word: "Je ... desto", translation: "كلما ... كلما" },
    { id: 595, word: "Damit", translation: "لكي" },
    { id: 596, word: "Insofern", translation: "بقدر ما" },
    { id: 597, word: "Gleichwohl", translation: "مع ذلك" },
    { id: 598, word: "Lediglich", translation: "فقط / ليس إلا" },
    { id: 599, word: "Zudem", translation: "علاوة على ذلك" },
    { id: 600, word: "Allerdings", translation: "مع ذلك / بالطبع" },
    // --- B2: Upper Intermediate Proficiency ---
    { id: 601, word: "Gewissen", translation: "ضمير" },
    { id: 602, word: "Konflikt", translation: "صراع / نزاع" },
    { id: 603, word: "Haltung", translation: "موقف / اِتجاه" },
    { id: 604, word: "Perspektive", translation: "منظور" },
    { id: 605, word: "Identität", translation: "هوية" },
    { id: 606, word: "Vielfalt", translation: "تنوع" },
    { id: 607, word: "Toleranz", translation: "تسامح" },
    { id: 608, word: "Integration", translation: "اِندماج" },
    { id: 609, word: "Ausgrenzung", translation: "اِستبعاد / تهميش" },
    { id: 610, word: "Gerechtigkeit", translation: "عدالة" },
    { id: 611, word: "Ungerechtigkeit", translation: "ظلم" },
    { id: 612, word: "Demokratie", translation: "ديمقراطية" },
    { id: 613, word: "Diktatur", translation: "ديكتاتورية" },
    { id: 614, word: "Bürgerkrieg", translation: "حرب أهلية" },
    { id: 615, word: "Wahl", translation: "اِنتخاب" },
    { id: 616, word: "Regierung", translation: "حكومة" },
    { id: 617, word: "Gesetz", translation: "قانون" },
    { id: 618, word: "Verfassung", translation: "دستور" },
    { id: 619, word: "Steuer", translation: "ضريبة" },
    { id: 620, word: "Globalisierung", translation: "عولمة" },
    { id: 621, word: "Kapitalismus", translation: "رأسمالية" },
    { id: 622, word: "Sozialismus", translation: "اِشتراكية" },
    { id: 623, word: "Ressource", translation: "مصدر / مورد" },
    { id: 624, word: "Konkurrenz", translation: "منافسة" },
    { id: 625, word: "Nachfrage", translation: "طلب (اِقتصادي)" },
    { id: 626, word: "Angebot", translation: "عرض (اِقتصادي)" },
    { id: 627, word: "Inflation", translation: "تضخم (اِقتصادي)" },
    { id: 628, word: "Deflation", translation: "اِنكماش (اِقتصادي)" },
    { id: 629, word: "Arbeitslosigkeit", translation: "بطالة" },
    { id: 630, word: "Ausschuss", translation: "لجنة / نفايات" },
    { id: 631, word: "Begleiten", translation: "يرافق" },
    { id: 632, word: "Bewältigen", translation: "يتغلب على / يتعامل مع" },
    { id: 633, word: "Ermitteln", translation: "يستكشف / يحقق" },
    { id: 634, word: "Erwerben", translation: "يكتسب" },
    { id: 635, word: "Feststellen", translation: "يُحدد / يكتشف" },
    { id: 636, word: "Handeln", translation: "يعمل / يتاجر" },
    { id: 637, word: "Hervorheben", translation: "يُبرز / يشدد على" },
    { id: 638, word: "Konstatieren", translation: "يلاحظ / يؤكد" },
    { id: 639, word: "Legitimieren", translation: "يُشرعن" },
    { id: 640, word: "Nachweisen", translation: "يُثبت / يقدم دليلاً" },
    { id: 641, word: "Provozieren", translation: "يستفز" },
    { id: 642, word: "Reflektieren", translation: "يتأمل / يعكس" },
    { id: 643, word: "Schildern", translation: "يصف / يروي" },
    { id: 644, word: "Schlussfolgern", translation: "يستنتج" },
    { id: 645, word: "Tragen", translation: "يتحمل / يحمل" },
    { id: 646, word: "Überwachen", translation: "يراقب" },
    { id: 647, word: "Unterbinden", translation: "يمنع / يعيق" },
    { id: 648, word: "Verfassen", translation: "يؤلف / يكتب" },
    { id: 649, word: "Vertreten", translation: "يمثل / يدافع عن" },
    { id: 650, word: "Vollziehen", translation: "ينفذ" },
    { id: 651, word: "Widerlegen", translation: "يدحض" },
    { id: 652, word: "Zulassen", translation: "يسمح بـ" },
    { id: 653, word: "Zugänglich", translation: "متاح / يمكن الوصول إليه" },
    { id: 654, word: "Erheblich", translation: "ملحوظ / مهم" },
    { id: 655, word: "Zweifellos", translation: "بلا شك" },
    { id: 656, word: "Authentisch", translation: "أصلي / موثوق" },
    { id: 657, word: "Subtil", translation: "دقيق / خفي" },
    { id: 658, word: "Eindeutig", translation: "لا لبس فيه" },
    { id: 659, word: "Heterogen", translation: "غير متجانس" },
    { id: 660, word: "Homogen", translation: "متجانس" },
    { id: 661, word: "Obligatorisch", translation: "إلزامي" },
    { id: 662, word: "Optional", translation: "اِختياري" },
    { id: 663, word: "Präzise", translation: "دقيق" },
    { id: 664, word: "Relevant", translation: "مهم / ذو صلة" },
    { id: 665, word: "Spekulativ", translation: "تخميني" },
    { id: 666, word: "Tendenziell", translation: "نزوعي / يميل إلى" },
    { id: 667, word: "Unverzichtbar", translation: "لا غنى عنه" },
    { id: 668, word: "Verbindlich", translation: "ملزم" },
    { id: 669, word: "Vorläufig", translation: "مؤقت / أولي" },
    { id: 670, word: "Zwiespältig", translation: "مزدوج / متناقض" },
    { id: 671, word: "Anhand", translation: "باِستخدام / بناءً على" },
    { id: 672, word: "Angesichts", translation: "نظراً لـ" },
    { id: 673, word: "Hinsichtlich", translation: "فيما يتعلق بـ" },
    { id: 674, word: "Infolge", translation: "نتيجة لـ" },
    { id: 675, word: "Mithilfe", translation: "بمساعدة" },
    { id: 676, word: "Zufolge", translation: "وفقاً لـ" },
    { id: 677, word: "Beispielsweise", translation: "على سبيل المثال" },
    { id: 678, word: "Demzufolge", translation: "وبناءً على ذلك" },
    { id: 679, word: "Ferner", translation: "علاوة على ذلك" },
    { id: 680, word: "Im Gegenteil", translation: "على العكس" },
    { id: 681, word: "In der Tat", translation: "في الواقع" },
    { id: 682, word: "Zwar", translation: "في الواقع (للتناقض)" },
    { id: 683, word: "Gleichzeitig", translation: "في الوقت نفسه" },
    { id: 684, word: "Indessen", translation: "في هذه الأثناء" },
    { id: 685, word: "Sobald", translation: "بمجرد أن" },
    { id: 686, word: "Solange", translation: "طالما" },
    { id: 687, word: "Bevor", translation: "قبل أن" },
    { id: 688, word: "Nachdem", translation: "بعد أن" },
    { id: 689, word: "Umso mehr", translation: "بالأحرى / أكثر من ذلك" },
    { id: 690, word: "Anscheinend", translation: "على ما يبدو" },
    { id: 691, word: "Offenbar", translation: "من الواضح" },
    { id: 692, word: "Tatsächlich", translation: "في الواقع" },
    { id: 693, word: "Unbedingt", translation: "بالتأكيد / حتماً" },
    { id: 694, word: "Vermutlich", translation: "على الأرجح" },
    { id: 695, word: "Zweifelsfrei", translation: "بلا أدنى شك" },
    { id: 696, word: "Schließlich", translation: "في نهاية المطاف" },
    { id: 697, word: "Hingegen", translation: "بالمقابل" },
    { id: 698, word: "Gegensatz", translation: "تناقض / تباين" },
    { id: 699, word: "Tendenz", translation: "ميل / اِتجاه" },
    { id: 700, word: "Norm", translation: "معيار / قاعدة" },
    { id: 701, word: "Substanz", translation: "جوهر / مادة" },
    { id: 702, word: "Paradox", translation: "مفارقة" },
    { id: 703, word: "Hypothese", translation: "فرضية" },
    { id: 704, word: "These", translation: "أطروحة" },
    { id: 705, word: "Metapher", translation: "اِستعارة" },
    { id: 706, word: "Ironie", translation: "سخرية / تهكم" },
    { id: 707, word: "Zynismus", translation: "سخرية لاذعة" },
    { id: 708, word: "Anekdote", translation: "حكاية" },
    { id: 709, word: "Plagiat", translation: "اِنتحال" },
    { id: 710, word: "Literatur", translation: "أدب" },
    { id: 711, word: "Philosophie", translation: "فلسفة" },
    { id: 712, word: "Ethik", translation: "أخلاق" },
    { id: 713, word: "Moral", translation: "معنويات / أخلاق" },
    { id: 714, word: "Ästhetik", translation: "جماليات" },
    { id: 715, word: "Logik", translation: "منطق" },
    { id: 716, word: "Rationalität", translation: "عقلانية" },
    { id: 717, word: "Emotion", translation: "عاطفة" },
    { id: 718, word: "Intuition", translation: "حدس" },
    { id: 719, word: "Bewusstsein", translation: "وعي" },
    { id: 720, word: "Unterbewusstsein", translation: "لاوعي" },
    { id: 721, word: "Gedächtnis", translation: "ذاكرة" },
    { id: 722, word: "Wahrnehmung", translation: "إدراك" },
    { id: 723, word: "Illusion", translation: "وهم" },
    { id: 724, word: "Realität", translation: "واقع" },
    { id: 725, word: "Existenz", translation: "وجود" },
    { id: 726, word: "Konzept", translation: "مفهوم" },
    { id: 727, word: "Theorie", translation: "نظرية" },
    { id: 728, word: "Praxis", translation: "ممارسة" },
    { id: 729, word: "Methode", translation: "منهجية" },
    { id: 730, word: "Prozedur", translation: "إجراء" },
    { id: 731, word: "Komponente", translation: "عنصر / مُكوّن" },
    { id: 732, word: "Struktur", translation: "بنية / هيكل" },
    { id: 733, word: "System", translation: "نظام" },
    { id: 734, word: "Netzwerk", translation: "شبكة" },
    { id: 735, word: "Interaktion", translation: "تفاعل" },
    { id: 736, word: "Kooperation", translation: "تعاون" },
    { id: 737, word: "Wettbewerb", translation: "منافسة" },
    { id: 738, word: "Monopol", translation: "اِحتكار" },
    { id: 739, word: "Subvention", translation: "دعم مالي" },
    { id: 740, word: "Zoll", translation: "رسوم جمركية" },
    { id: 741, word: "Handelsabkommen", translation: "اِتفاقية تجارية" },
    { id: 742, word: "Diplomatie", translation: "دبلوماسية" },
    { id: 743, word: "Souveränität", translation: "سيادة" },
    { id: 744, word: "Protest", translation: "اِحتجاج" },
    { id: 745, word: "Demonstration", translation: "مظاهرة" },
    { id: 746, word: "Revolution", translation: "ثورة" },
    { id: 747, word: "Reform", translation: "إصلاح" },
    { id: 748, word: "Tradition", translation: "تقاليد" },
    { id: 749, word: "Moderne", translation: "حداثة" },
    { id: 750, word: "Renaissance", translation: "نهضة" },
    { id: 751, word: "Epoche", translation: "حقبة / عصر" },
    { id: 752, word: "Zeitalter", translation: "عصر" },
    { id: 753, word: "Mythos", translation: "أسطورة" },
    { id: 754, word: "Ritual", translation: "طقس" },
    { id: 755, word: "Zeremonie", translation: "مراسم" },
    { id: 756, word: "Spiritualität", translation: "روحانية" },
    { id: 757, word: "Säkularisierung", translation: "عَلْمنة" },
    { id: 758, word: "Dogma", translation: "عقيدة / مُسلَّمة" },
    { id: 759, word: "Predigt", translation: "خطبة / موعظة" },
    { id: 760, word: "Priester", translation: "كاهن" },
    { id: 761, word: "Konsum", translation: "اِستهلاك" },
    { id: 762, word: "Werbung", translation: "إعلان" },
    { id: 763, word: "Marke", translation: "علامة تجارية" },
    { id: 764, word: "Trend", translation: "اِتجاه" },
    { id: 765, word: "Massenmedien", translation: "وسائل اِلإعلام الجماهيرية" },
    { id: 766, word: "Propaganda", translation: "دعاية" },
    { id: 767, word: "Zensur", translation: "رقابة" },
    { id: 768, word: "Ethnozentrismus", translation: "اِستعراقية" },
    { id: 769, word: "Diskriminierung", translation: "تمييز" },
    { id: 770, word: "Vorurteil", translation: "اِنحياز / حكم مسبق" },
    { id: 771, word: "Stereotyp", translation: "صورة نمطية" },
    { id: 772, word: "Flüchtling", translation: "لاجئ" },
    { id: 773, word: "Migration", translation: "هجرة" },
    { id: 774, word: "Asyl", translation: "لجوء" },
    { id: 775, word: "Staatsbürgerschaft", translation: "مواطنة" },
    { id: 776, word: "Bürokratie", translation: "بيروقراطية" },
    { id: 777, word: "Effizienz", translation: "كفاءة" },
    { id: 778, word: "Transparenz", translation: "شفافية" },
    { id: 779, word: "Korruption", translation: "فساد" },
    { id: 780, word: "Skandal", translation: "فضيحة" },
    { id: 781, word: "Manipulation", translation: "تلاعب" },
    { id: 782, word: "Genugtuung", translation: "اِرتياح / اِعتذار" },
    { id: 783, word: "Widerspruch", translation: "تناقض / اِعتراض" },
    { id: 784, word: "Gegenüberstellung", translation: "مواجهة / مقارنة" },
    { id: 785, word: "Kontroverse", translation: "جدل / خلاف" },
    { id: 786, word: "Debatte", translation: "مناظرة" },
    { id: 787, word: "Verhandlung", translation: "مفاوضة" },
    { id: 788, word: "Einigung", translation: "اِتفاق" },
    { id: 789, word: "Konzession", translation: "تنازل" },
    { id: 790, word: "Kompromiss", translation: "حل وسط" },
    { id: 791, word: "Initiative", translation: "مبادرة" },
    { id: 792, word: "Engagement", translation: "اِلتزام / اِنخراط" },
    { id: 793, word: "Motivation", translation: "دافع / حافز" },
    { id: 794, word: "Selbstvertrauen", translation: "ثقة بالنفس" },
    { id: 795, word: "Selbstbewusstsein", translation: "وعي ذاتي / ثقة" },
    { id: 796, word: "Frustration", translation: "إحباط" },
    { id: 797, word: "Einsamkeit", translation: "وحدة / اِنعزال" },
    { id: 798, word: "Sucht", translation: "إدمان" },
    { id: 799, word: "Therapie", translation: "علاج" },
    { id: 800, word: "Diagnose", translation: "تشخيص" },
    { id: 801, word: "Prävention", translation: "وقاية" },
    { id: 802, word: "Rehabilitation", translation: "إعادة تأهيل" },
    { id: 803, word: "Genesung", translation: "اِستشفاء" },
    { id: 804, word: "Lebensstandard", translation: "مستوى المعيشة" },
    { id: 805, word: "Armut", translation: "فقر" },
    { id: 806, word: "Reichtum", translation: "ثراء" },
    { id: 807, word: "Einkommen", translation: "دخل" },
    { id: 808, word: "Vermögen", translation: "ثروة" },
    { id: 809, word: "Schuld (Debt/Guilt)", translation: "دَين / ذنب" },
    { id: 810, word: "Haftung", translation: "مسؤولية قانونية" },
    { id: 811, word: "Anklage", translation: "اِتهام" },
    { id: 812, word: "Urteil", translation: "حكم قضائي" },
    { id: 813, word: "Freispruch", translation: "تبرئة" },
    { id: 814, word: "Verbrechen", translation: "جريمة" },
    { id: 815, word: "Straftat", translation: "مخالفة جنائية" },
    { id: 816, word: "Zeuge", translation: "شاهد" },
    { id: 817, word: "Beweis", translation: "دليل" },
    { id: 818, word: "Ermittlung", translation: "تحقيق" },
    { id: 819, word: "Verfolgen", translation: "يطارد / يلاحق" },
    { id: 820, word: "Fliehen", translation: "يهرب" },
    { id: 821, word: "Verbergen", translation: "يخفي" },
    { id: 822, word: "Offenbaren", translation: "يكشف / يُعلن" },
    { id: 823, word: "Vorgehen", translation: "اِجراء / طريقة عمل" },
    { id: 824, word: "Maßnahme", translation: "إجراء / تدبير" },
    { id: 825, word: "Strategie", translation: "اِستراتيجية" },
    { id: 826, word: "Taktik", translation: "تكتيك" },
    { id: 827, word: "Planung", translation: "تخطيط" },
    { id: 828, word: "Organisation", translation: "تنظيم" },
    { id: 829, word: "Koordination", translation: "تنسيق" },
    { id: 830, word: "Delegation", translation: "تفويض" },
    { id: 831, word: "Priorität", translation: "أولوية" },
    { id: 832, word: "Terminologie", translation: "مصطلحات" },
    { id: 833, word: "Kontext", translation: "سياق" },
    { id: 834, word: "Interpretation", translation: "تفسير" },
    { id: 835, word: "Analyse", translation: "تحليل" },
    { id: 836, word: "Synthese", translation: "تركيب" },
    { id: 837, word: "Quantität", translation: "كمية" },
    { id: 838, word: "Qualität", translation: "جودة" },
    { id: 839, word: "Standard", translation: "معيار" },
    { id: 840, word: "Abweichung", translation: "اِنحراف" },
    { id: 841, word: "Statistik", translation: "إحصاء" },
    { id: 842, word: "Durchschnitt", translation: "متوسط" },
    { id: 843, word: "Median", translation: "وسيط" },
    { id: 844, word: "Kausalität", translation: "سببية" },
    { id: 845, word: "Korrelation", translation: "اِرتباط" },
    { id: 846, word: "Stichprobe", translation: "عينة" },
    { id: 847, word: "Repräsentativ", translation: "ممثِّل" },
    { id: 848, word: "Validität", translation: "صلاحية" },
    { id: 849, word: "Reliabilität", translation: "موثوقية" },
    { id: 850, word: "Objektivität", translation: "موضوعية" },
    { id: 851, word: "Subjektivität", translation: "ذاتية" },
    { id: 852, word: "Neutralität", translation: "حياد" },
    { id: 853, word: "Parteilichkeit", translation: "اِنحياز" },
    { id: 854, word: "Ethisch", translation: "أخلاقي" },
    { id: 855, word: "Unethisch", translation: "غير أخلاقي" },
    { id: 856, word: "Moralisch", translation: "معنوي / أخلاقي" },
    { id: 857, word: "Immoralisch", translation: "لا أخلاقي" },
    { id: 858, word: "Vorbild", translation: "قدوة / مثال" },
    { id: 859, word: "Nachahmung", translation: "تقليد" },
    { id: 860, word: "Innovation", translation: "اِبتكار" },
    { id: 861, word: "Traditionell", translation: "تقليدي" },
    { id: 862, word: "Zeitgenössisch", translation: "معاصر" },
    { id: 863, word: "Konservativ", translation: "محافظ" },
    { id: 864, word: "Liberal", translation: "ليبرالي / متحرر" },
    { id: 865, word: "Radikal", translation: "جذري" },
    { id: 866, word: "Extrem", translation: "متطرف" },
    { id: 867, word: "Gemäßigt", translation: "معتدل" },
    { id: 868, word: "Autonom", translation: "مستقل ذاتياً" },
    { id: 869, word: "Abhängig", translation: "تابع / معتمد" },
    { id: 870, word: "Spezifisch", translation: "محدد" },
    { id: 871, word: "Allgemein", translation: "عام" },
    { id: 872, word: "Potenziell", translation: "محتمل" },
    { id: 873, word: "Tatsächlich", translation: "فعلي" },
    { id: 874, word: "Fiktiv", translation: "خيالي" },
    { id: 875, word: "Verbinden", translation: "يربط / يصل" },
    { id: 876, word: "Trennen", translation: "يفصل" },
    { id: 877, word: "Ermöglichen", translation: "يُمكّن" },
    { id: 878, word: "Verhindern", translation: "يمنع" },
    { id: 879, word: "Einbeziehen", translation: "يُشرك / يشمل" },
    { id: 880, word: "Ausschließen", translation: "يستبعد" },
    { id: 881, word: "Generieren", translation: "يولد / ينتج" },
    { id: 882, word: "Konsumieren", translation: "يستهلك" },
    { id: 883, word: "Regulieren", translation: "ينظم" },
    { id: 884, word: "Dezentralisieren", translation: "يُقلل المركزية" },
    { id: 885, word: "Rationalisieren", translation: "يُرشّد / يعقلن" },
    { id: 886, word: "Sensibilisieren", translation: "يُوعّي / يحسّس" },
    { id: 887, word: "Stabilisieren", translation: "يُثبّت" },
    { id: 888, word: "Subventionieren", translation: "يدعم مالياً" },
    { id: 889, word: "Visualisieren", translation: "يتصور / يجسد" },
    { id: 890, word: "Zertifizieren", translation: "يُصادق / يمنح شهادة" },
    { id: 891, word: "Erhebt sich", translation: "ينهض / يثور" },
    { id: 892, word: "Unterliegt", translation: "يخضع لـ" },
    { id: 893, word: "Zieht in Betracht", translation: "يأخذ بعين الاِعتبار" },
    { id: 894, word: "Tritt in Kraft", translation: "يدخل حيز التنفيذ" },
    { id: 895, word: "Übereinstimmen", translation: "يتفق مع" },
    { id: 896, word: "Verursachen", translation: "يسبب" },
    { id: 897, word: "Gewährleisten", translation: "يضمن" },
    { id: 898, word: "Einleiten", translation: "يستهل / يبدأ" },
    { id: 899, word: "Verfahren", translation: "إجراء / قضية" },
    { id: 900, word: "Aussage", translation: "قول / بيان" },
    { id: 901, word: "Schlussfolgerung", translation: "اِستنتاج" },
    { id: 902, word: "Zusammenfassung", translation: "ملخص" },
    { id: 903, word: "Quell(e)", translation: "مصدر" },
    { id: 904, word: "Beleg", translation: "وثيقة / إثبات" },
    { id: 905, word: "Zitieren", translation: "يقتبس" },
    { id: 906, word: "Referenz", translation: "مرجع" },
    { id: 907, word: "Datenbasis", translation: "قاعدة بيانات" },
    { id: 908, word: "Modell", translation: "نموذج" },
    { id: 909, word: "Simulation", translation: "محاكاة" },
    { id: 910, word: "Variable", translation: "متغير" },
    { id: 911, word: "Parameter", translation: "معامل" },
    { id: 912, word: "Symptom", translation: "عرض" },
    { id: 913, word: "Phänomen", translation: "ظاهرة" },
    { id: 914, word: "Komplexität", translation: "تعقيد" },
    { id: 915, word: "Diversität", translation: "تنوع" },
    { id: 916, word: "Ambivalenz", translation: "اِزدواجية المشاعر" },
    { id: 917, word: "Integrität", translation: "نزاهة / اِستقامة" },
    { id: 918, word: "Priorisierung", translation: "تحديد الأولويات" },
    { id: 919, word: "Kapazität", translation: "سعة / قدرة" },
    { id: 920, word: "Rendite", translation: "عائد / ربح" },
    { id: 921, word: "Defizit", translation: "عجز" },
    { id: 922, word: "Überschuss", translation: "فائض" },
    { id: 923, word: "Bilanz", translation: "ميزانية" },
    { id: 924, word: "Kapital", translation: "رأس مال" },
    { id: 925, word: "Investition", translation: "اِستثمار" },
    { id: 926, word: "Aktie", translation: "سهم" },
    { id: 927, word: "Anleihe", translation: "سند" },
    { id: 928, word: "Währung", translation: "عملة" },
    { id: 929, word: "Börse", translation: "بورصة" },
    { id: 930, word: "Spekulation", translation: "مضاربة" },
    { id: 931, word: "Risiko", translation: "خطر" },
    { id: 932, word: "Absicherung", translation: "تحوط / حماية" },
    { id: 933, word: "Fonds", translation: "صندوق مالي" },
    { id: 934, word: "Portfolio", translation: "محفظة" },
    { id: 935, word: "Kredit", translation: "قرض" },
    { id: 936, word: "Zins(satz)", translation: "معدل فائدة" },
    { id: 937, word: "Rating", translation: "تصنيف اِئتماني" },
    { id: 938, word: "Fusion", translation: "اِندماج" },
    { id: 939, word: "Übernahme", translation: "اِستحواذ" },
    { id: 940, word: "Sanierung", translation: "إعادة هيكلة / ترميم" },
    { id: 941, word: "Restrukturierung", translation: "إعادة هيكلة" },
    { id: 942, word: "Outsourcing", translation: "اِسناد خارجي" },
    { id: 943, word: "Insourcing", translation: "اِسناد داخلي" },
    { id: 944, word: "Digitalisierung", translation: "رقمنة" },
    { id: 945, word: "Automatisierung", translation: "أتمتة" },
    { id: 946, word: "Künstliche Intelligenz (KI)", translation: "ذكاء اِصطناعي" },
    { id: 947, word: "Big Data", translation: "بيانات ضخمة" },
    { id: 948, word: "Algorithmus", translation: "خوارزمية" },
    { id: 949, word: "Datenschutz", translation: "حماية البيانات" },
    { id: 950, word: "Urheberrecht", translation: "حقوق النشر" },
    { id: 951, word: "Patent", translation: "براءة اِختراع" },
    { id: 952, word: "Markenrecht", translation: "قانون العلامات التجارية" },
    { id: 953, word: "Lizenzen", translation: "تراخيص" },
    { id: 954, word: "Compliance", translation: "اِمتثال" },
    { id: 955, word: "Reglementierung", translation: "تنظيم / تقنين" },
    { id: 956, word: "Beweislast", translation: "عبء الإثبات" },
    { id: 957, word: "Zwang", translation: "إكراه / إجبار" },
    { id: 958, word: "Willkür", translation: "تعسف / اِستبداد" },
    { id: 959, word: "Subjektiv", translation: "ذاتي" },
    { id: 960, word: "Objektiv", translation: "موضوعي" },
    { id: 961, word: "Ethisch", translation: "أخلاقي" },
    { id: 962, word: "Logisch", translation: "منطقي" },
    { id: 963, word: "Systematisch", translation: "منهجي" },
    { id: 964, word: "Intuitiv", translation: "حدسي" },
    { id: 965, word: "Empirisch", translation: "تجريبي" },
    { id: 966, word: "Theoretisch", translation: "نظري" },
    { id: 967, word: "Praktikabel", translation: "قابل للتطبيق" },
    { id: 968, word: "Konsequent", translation: "متسق / ثابت" },
    { id: 969, word: "Inkonsequent", translation: "غير متسق" },
    { id: 970, word: "Plausibel", translation: "معقول / جدير بالتصديق" },
    { id: 971, word: "Unplausibel", translation: "غير معقول" },
    { id: 972, word: "Auffällig", translation: "ملفت للنظر" },
    { id: 973, word: "Unauffällig", translation: "غير ملفت للنظر" },
    { id: 974, word: "Verbindend", translation: "جامع / موحد" },
    { id: 975, word: "Trennend", translation: "فاصل" },
    { id: 976, word: "Förderlich", translation: "مساعد / معزز" },
    { id: 977, word: "Hinderlich", translation: "معيق" },
    { id: 978, word: "Angespannt", translation: "متوتر" },
    { id: 979, word: "Entspannt", translation: "مسترخ" },
    { id: 980, word: "Begeistert", translation: "متحمس" },
    { id: 981, word: "Desinteressiert", translation: "غير مهتم" },
    { id: 982, word: "Ernsthaft", translation: "جدي" },
    { id: 983, word: "Humorvoll", translation: "فكاهي" },
    { id: 984, word: "Gelassen", translation: "هادئ الأعصاب" },
    { id: 985, word: "Skeptisch", translation: "متشكك" },
    { id: 986, word: "Zuversichtlich", translation: "واثق" },
    { id: 987, word: "Nachdenklich", translation: "متأمل" },
    { id: 988, word: "Klarheit", translation: "وضوح" },
    { id: 989, word: "Unklarheit", translation: "غموض" },
    { id: 990, word: "Präzision", translation: "دقة" },
    { id: 991, word: "Ambiguität", translation: "غموض / اِبهام" },
    { id: 992, word: "Redundanz", translation: "زيادة / حشو" },
    { id: 993, word: "Synthese", translation: "توليف" },
    { id: 994, word: "Divergenz", translation: "اِختلاف / تباعد" },
    { id: 995, word: "Konvergenz", translation: "تقارب" },
    { id: 996, word: "Dilemma", translation: "معضلة" },
    { id: 997, word: "Ersatz", translation: "بديل" },
    { id: 998, word: "Rolle", translation: "دور" },
    { id: 999, word: "Anspruch", translation: "حق / مطلب" },
    { id: 1000, word: "Einsatz", translation: "اِستخدام / اِنخراط" }
  ],
  advanced: [
    // --- C1: Advanced Proficiency ---
    { id: 1001, word: "Implikation", translation: "تضمين / دلالة" },
    { id: 1002, word: "Kognition", translation: "إدراك / معرفة" },
    { id: 1003, word: "Affinität", translation: "اِنجذاب / تقارب" },
    { id: 1004, word: "Ambivalenz", translation: "اِزدواجية" },
    { id: 1005, word: "Ressentiment", translation: "اِستياء عميق" },
    { id: 1006, word: "Prärogative", translation: "اِمتياز / حق خاص" },
    { id: 1007, word: "Konsens", translation: "اِجماع" },
    { id: 1008, word: "Divergenz", translation: "اِختلاف / تباعد" },
    { id: 1009, word: "Dialektik", translation: "جدلية" },
    { id: 1010, word: "Exposé", translation: "عرض موجز / كشف" },
    { id: 1011, word: "Subversion", translation: "تخريب / هدم" },
    { id: 1012, word: "Konjunktur", translation: "اِزدهار اِقتصادي" },
    { id: 1013, word: "Rezession", translation: "ركود اِقتصادي" },
    { id: 1014, word: "Hegemonie", translation: "هيمنة" },
    { id: 1015, word: "Säkularisierung", translation: "علمنة" },
    { id: 1016, word: "Postulat", translation: "مسلّمة / اِفتراض" },
    { id: 1017, word: "Determinismus", translation: "حتمية" },
    { id: 1018, word: "Kontingenz", translation: "اِحتِمال / طارئ" },
    { id: 1019, word: "Präzedenzfall", translation: "سابقة قانونية" },
    { id: 1020, word: "Jurisprudenz", translation: "فقه قانوني" },
    { id: 1021, word: "Äquivalenz", translation: "تكافؤ" },
    { id: 1022, word: "Synthese", translation: "توليف / تركيب" },
    { id: 1023, word: "Antithese", translation: "نقيض" },
    { id: 1024, word: "Akribie", translation: "دقة متناهية" },
    { id: 1025, word: "Elaborieren", translation: "يشرح بالتفصيل" },
    { id: 1026, word: "Konstatieren", translation: "يُثبت / يلاحظ" },
    { id: 1027, word: "Eruieren", translation: "يستكشف / يتحقق" },
    { id: 1028, word: "Rezipieren", translation: "يستقبل / يتلقى" },
    { id: 1029, word: "Implizieren", translation: "يُضمر / يعني ضمناً" },
    { id: 1030, word: "Destillieren", translation: "يقطر / يستخلص" },
    { id: 1031, word: "Extrapolieren", translation: "يستنبط بالقياس" },
    { id: 1032, word: "Relativieren", translation: "ينسب / يجعل نسبياً" },
    { id: 1033, word: "Deuten", translation: "يفسر / يؤول" },
    { id: 1034, word: "Konvergieren", translation: "يتقارب" },
    { id: 1035, word: "Divergieren", translation: "يتباعد" },
    { id: 1036, word: "Legitimieren", translation: "يُشرعن" },
    { id: 1037, word: "Delegitimieren", translation: "ينزع الشرعية" },
    { id: 1038, word: "Transzendieren", translation: "يتجاوز" },
    { id: 1039, word: "Sublimieren", translation: "يُسامي" },
    { id: 1040, word: "Affirmieren", translation: "يؤكد اِيجابياً" },
    { id: 1041, word: "Adäquat", translation: "مناسب / كافٍ" },
    { id: 1042, word: "Peripher", translation: "محيطي / ثانوي" },
    { id: 1043, word: "Eklatant", translation: "فاضح / صارخ" },
    { id: 1044, word: "Nugatorisch", translation: "تافه / لا قيمة له" },
    { id: 1045, word: "Ponderös", translation: "ثقيل / ضخم" },
    { id: 1046, word: "Ominös", translation: "مشؤوم" },
    { id: 1047, word: "Lapidar", translation: "موجز ومُعبّر" },
    { id: 1048, word: "Ambivalent", translation: "متناقض المشاعر" },
    { id: 1049, word: "Axiomatisch", translation: "بديهي" },
    { id: 1050, word: "Ausschließlich", translation: "حصرياً" },
    { id: 1051, word: "Weitreichend", translation: "بعيد المدى" },
    { id: 1052, word: "Diktatorisch", translation: "ديكتاتوري" },
    { id: 1053, word: "Singulär", translation: "فردي / فريد" },
    { id: 1054, word: "Akzentuiert", translation: "مشدد عليه" },
    { id: 1055, word: "Proportional", translation: "متناسب" },
    { id: 1056, word: "Disproportional", translation: "غير متناسب" },
    { id: 1057, word: "Chronologisch", translation: "حسب التسلسل الزمني" },
    { id: 1058, word: "Synonym", translation: "مرادف" },
    { id: 1059, word: "Antonym", translation: "متضاد" },
    { id: 1060, word: "Syntaktisch", translation: "نحوي" },
    { id: 1061, word: "Semantisch", translation: "دلالي" },
    { id: 1062, word: "Pragmatisch", translation: "عملي / واقعي" },
    { id: 1063, word: "Epistemologie", translation: "نظرية المعرفة" },
    { id: 1064, word: "Ontologie", translation: "علم الوجود" },
    { id: 1065, word: "Ästhetizismus", translation: "جمالية" },
    { id: 1066, word: "Nihilismus", translation: "عدمية" },
    { id: 1067, word: "Existentialismus", translation: "وجودية" },
    { id: 1068, word: "Rationalismus", translation: "عقلانية" },
    { id: 1069, word: "Empirismus", translation: "تجريبية" },
    { id: 1070, word: "Metaphysik", translation: "ما وراء الطبيعة" },
    { id: 1071, word: "A priori", translation: "قبلي / بشكل اِستدلالي" },
    { id: 1072, word: "A posteriori", translation: "بعدي / بشكل تجريبي" },
    { id: 1073, word: "Falsifikation", translation: "تفنيد / دحض" },
    { id: 1074, word: "Induktion", translation: "اِستقراء" },
    { id: 1075, word: "Deduktion", translation: "اِستنتاج" },
    { id: 1076, word: "Hermeneutik", translation: "علم التفسير والتأويل" },
    { id: 1077, word: "Diskurs", translation: "خطاب / نقاش" },
    { id: 1078, word: "Paradigma", translation: "نموذج فكري" },
    { id: 1079, word: "Narrativ", translation: "سرد / قصة" },
    { id: 1080, word: "Rezeption", translation: "اِستقبال / اِستيعاب" },
    { id: 1081, word: "Dichotomie", translation: "اِنقسام ثنائي" },
    { id: 1082, word: "Homologie", translation: "تشابه / تماثل" },
    { id: 1083, word: "Heteronomie", translation: "اِعتماد على الغير" },
    { id: 1084, word: "Autonomie", translation: "اِستقلال ذاتي" },
    { id: 1085, word: "Konnotation", translation: "دلالة اِضافية" },
    { id: 1086, word: "Denotation", translation: "دلالة أساسية" },
    { id: 1087, word: "Reduktionismus", translation: "اِختزالية" },
    { id: 1088, word: "Holismus", translation: "شمولية" },
    { id: 1089, word: "Kausalzusammenhang", translation: "اِرتباط سببي" },
    { id: 1090, word: "Korrelation", translation: "اِرتباط" },
    { id: 1091, word: "Statussymbol", translation: "رمز للمكانة" },
    { id: 1092, word: "Sozioökonomisch", translation: "اِجتماعي اِقتصادي" },
    { id: 1093, word: "Partizipation", translation: "مشاركة" },
    { id: 1094, word: "Intervention", translation: "تدخل" },
    { id: 1095, word: "Emanzipation", translation: "تحرر" },
    { id: 1096, word: "Indoktrinieren", translation: "يلقن / يغرس عقيدة" },
    { id: 1097, word: "Propagieren", translation: "ينشر / يروج" },
    { id: 1098, word: "Subventionieren", translation: "يدعم مالياً" },
    { id: 1099, word: "Ratifizieren", translation: "يُصادق على (اِتفاقية)" },
    { id: 1100, word: "Annulieren", translation: "يُلغي" },
    { id: 1101, word: "Dekret", translation: "مرسوم" },
    { id: 1102, word: "Plenum", translation: "اِجتماع مكتمل النصاب" },
    { id: 1103, word: "Mandat", translation: "تفويض / اِنتداب" },
    { id: 1104, word: "Legislative", translation: "السلطة التشريعية" },
    { id: 1105, word: "Exekutive", translation: "السلطة التنفيذية" },
    { id: 1106, word: "Judikative", translation: "السلطة القضائية" },
    { id: 1107, word: "Fiskalisch", translation: "مالي / ضريبي" },
    { id: 1108, word: "Monetär", translation: "نقدي" },
    { id: 1109, word: "Sanktion", translation: "عقوبة" },
    { id: 1110, word: "Boykott", translation: "مقاطعة" },
    { id: 1111, word: "Protektionismus", translation: "حمائية" },
    { id: 1112, word: "Freihandel", translation: "تجارة حرة" },
    { id: 1113, word: "Deregulierung", translation: "رفع القيود" },
    { id: 1114, word: "Prekariat", translation: "طبقة العمالة الهشة" },
    { id: 1115, word: "Prekär", translation: "هش / غير مستقر" },
    { id: 1116, word: "Konvergenz", translation: "تقارب" },
    { id: 1117, word: "Transparenz", translation: "شفافية" },
    { id: 1118, word: "Opazität", translation: "غموض / عتامة" },
    { id: 1119, word: "Rezidiv", translation: "اِنتكاس / نكسة" },
    { id: 1120, word: "Pathologisch", translation: "مرضي" },
    { id: 1121, word: "Ätiologie", translation: "علم أسباب الأمراض" },
    { id: 1122, word: "Prognose", translation: "تنبؤ / تشخيص مستقبلي" },
    { id: 1123, word: "Amnesie", translation: "فقدان الذاكرة" },
    { id: 1124, word: "Paranoia", translation: "جنون العظمة" },
    { id: 1125, word: "Neurose", translation: "عُصاب" },
    { id: 1126, word: "Psychose", translation: "ذهان" },
    { id: 1127, word: "Trauma", translation: "صدمة نفسية / جسدية" },
    { id: 1128, word: "Resilienz", translation: "مرونة نفسية" },
    { id: 1129, word: "Kompensation", translation: "تعويض" },
    { id: 1130, word: "Sublimierung", translation: "تسامي (دفاع نفسي)" },
    { id: 1131, word: "Assoziation", translation: "اِرتباط / تداعي" },
    { id: 1132, word: "Konditionierung", translation: "اِشتراط" },
    { id: 1133, word: "Habituierung", translation: "اِعتياد" },
    { id: 1134, word: "Verifikation", translation: "تحقق" },
    { id: 1135, word: "Validierung", translation: "توثيق / تأكيد الصلاحية" },
    { id: 1136, word: "Reliabilität", translation: "موثوقية" },
    { id: 1137, word: "Evidenz", translation: "دليل / بينة" },
    { id: 1138, word: "Fakultativ", translation: "اِختياري" },
    { id: 1139, word: "Obligatorisch", translation: "إلزامي" },
    { id: 1140, word: "Akzeptanz", translation: "قبول" },
    { id: 1141, word: "Ignorieren", translation: "يتجاهل" },
    { id: 1142, word: "Konfrontieren", translation: "يواجه" },
    { id: 1143, word: "Delegieren", translation: "يفوّض" },
    { id: 1144, word: "Involvieren", translation: "يُشرك" },
    { id: 1145, word: "Präventiv", translation: "وقائي" },
    { id: 1146, word: "Repressiv", translation: "قمعي" },
    { id: 1147, word: "Exorbitant", translation: "باهظ / مفرط" },
    { id: 1148, word: "Trivial", translation: "تافه / بسيط" },
    { id: 1149, word: "Erudition", translation: "علم / سعة اِطلاع" },
    { id: 1150, word: "Desiderat", translation: "أمنية / حاجة" },
    // --- C2: Near Native/Mastery Level ---
    { id: 1151, word: "Subsumieren", translation: "يُصنّف تحت (قاعدة)" },
    { id: 1152, word: "Konzedieren", translation: "يعترف / يقر" },
    { id: 1153, word: "Anerkennen", translation: "يُقر / يعترف بـ" },
    { id: 1154, word: "Affizieren", translation: "يؤثر في / يُصيب" },
    { id: 1155, word: "Exponieren", translation: "يعرض / يُكشّف" },
    { id: 1156, word: "Inszenieren", translation: "يُخرج / يُدبّر" },
    { id: 1157, word: "Persistieren", translation: "يُصر / يثابر" },
    { id: 1158, word: "Akquirieren", translation: "يستحوذ على / يكتسب" },
    { id: 1159, word: "Evaluieren", translation: "يُقيّم" },
    { id: 1160, word: "Kollidieren", translation: "يتصادم" },
    { id: 1161, word: "Rehabilitieren", translation: "يُعيد التأهيل" },
    { id: 1162, word: "Verifizieren", translation: "يتحقق من صحة" },
    { id: 1163, word: "Konterkarieren", translation: "يُحبط / يُعارض" },
    { id: 1164, word: "Legitim", translation: "شرعي" },
    { id: 1165, word: "Illegitim", translation: "غير شرعي" },
    { id: 1166, word: "Immanent", translation: "ملازم / كامن" },
    { id: 1167, word: "Transzendent", translation: "متجاوز / متعالٍ" },
    { id: 1168, word: "Singulär", translation: "فريد" },
    { id: 1169, word: "Pluralistisch", translation: "تعددي" },
    { id: 1170, word: "Integrativ", translation: "تكاملي" },
    { id: 1171, word: "Disruptiv", translation: "مُعطّل / مُخرب" },
    { id: 1172, word: "Synthetisch", translation: "تركيبي" },
    { id: 1173, word: "Analytisch", translation: "تحليلي" },
    { id: 1174, word: "Eklektisch", translation: "اِنتقائي" },
    { id: 1175, word: "Amorph", translation: "عديم الشكل" },
    { id: 1176, word: "Implizit", translation: "ضمنياً" },
    { id: 1177, word: "Explizit", translation: "صريحاً" },
    { id: 1178, word: "Akut", translation: "حاد / مُلح" },
    { id: 1179, word: "Chronisch", translation: "مزمن" },
    { id: 1180, word: "De jure", translation: "بحكم القانون" },
    { id: 1181, word: "De facto", translation: "في الواقع" },
    { id: 1182, word: "Epizentrum", translation: "مركز اِلإنتشار" },
    { id: 1183, word: "Subtext", translation: "نص ضمني" },
    { id: 1184, word: "Resonanz", translation: "صدى / رنين" },
    { id: 1185, word: "Amalgamierung", translation: "اِندماج / خلط" },
    { id: 1186, word: "Dissonanz", translation: "اِختلاف / نشاز" },
    { id: 1187, word: "Haptik", translation: "حس اللمس" },
    { id: 1188, word: "Oszillation", translation: "تذبذب" },
    { id: 1189, word: "Konstellation", translation: "تكوين / مجموعة ظروف" },
    { id: 1190, word: "Primat", translation: "أولوية / أسبقية" },
    { id: 1191, word: "Säkulum", translation: "قرن / مئة سنة" },
    { id: 1192, word: "Zeitgeist", translation: "روح العصر" },
    { id: 1193, word: "Existenzialität", translation: "وجودية" },
    { id: 1194, word: "Vulnerabilität", translation: "قابلية التعرض للخطر" },
    { id: 1195, word: "Transzendenz", translation: "تسامٍ / تجاوز" },
    { id: 1196, word: "Reziprozität", translation: "تبادلية" },
    { id: 1197, word: "Indifferenz", translation: "لا مبالاة" },
    { id: 1198, word: "Dichotomie", translation: "اِنقسام ثنائي" },
    { id: 1199, word: "Homogenisierung", translation: "تجنيس" },
    { id: 1200, word: "Anachronismus", translation: "مفارقة تاريخية" },
    { id: 1201, word: "Inaugurieren", translation: "يفتتح / يتولى منصباً" },
    { id: 1202, word: "Perpetuieren", translation: "يُديم / يخلد" },
    { id: 1203, word: "Assoziativ", translation: "اِرتباطي" },
    { id: 1204, word: "Euphemismus", translation: "تلطيف العبارة" },
    { id: 1205, word: "Pleonasmus", translation: "حشو (بلاغة)" },
    { id: 1206, word: "Synekdoche", translation: "مجاز مرسل" },
    { id: 1207, word: "Oxymoron", translation: "متناقض لفظي" },
    { id: 1208, word: "Allegorie", translation: "مجاز / قصة رمزية" },
    { id: 1209, word: "Parabel", translation: "مثل / حكاية رمزية" },
    { id: 1210, word: "Dystopie", translation: "مدينة فاضلة عكسية" },
    { id: 1211, word: "Utopie", translation: "مدينة فاضلة" },
    { id: 1212, word: "Konklusion", translation: "اِستنتاج" },
    { id: 1213, word: "Prämisse", translation: "مقدمة (منطق)" },
    { id: 1214, word: "Kritizismus", translation: "اِنتقادية" },
    { id: 1215, word: "Dogmatismus", translation: "تعصب عقائدي" },
    { id: 1216, word: "Nihilist", translation: "عدمي" },
    { id: 1217, word: "Stoizismus", translation: "رواقية" },
    { id: 1218, word: "Hedonismus", translation: "مذهب اللذة" },
    { id: 1219, word: "Egoismus", translation: "أنانية" },
    { id: 1220, word: "Altruismus", translation: "إيثار" },
    { id: 1221, word: "Ethnozentrisch", translation: "متمحور حول العرق" },
    { id: 1222, word: "Philanthropie", translation: "عمل الخير" },
    { id: 1223, word: "Empathie", translation: "تعاطف / اِستشعار" },
    { id: 1224, word: "Sympathie", translation: "تفاهم / تعاطف" },
    { id: 1225, word: "Apathie", translation: "لا مبالاة" },
    { id: 1226, word: "Konvention", translation: "اِتفاقية / عرف" },
    { id: 1227, word: "Usus", translation: "عرف / اِستخدام" },
    { id: 1228, word: "Protokoll", translation: "بروتوكول / محضر" },
    { id: 1229, word: "Deeskalation", translation: "تخفيف التصعيد" },
    { id: 1230, word: "Eskalation", translation: "تصعيد" },
    { id: 1231, word: "Konsolidieren", translation: "يوحد / يعزز" },
    { id: 1232, word: "Fragmentieren", translation: "يفتت / يجزئ" },
    { id: 1233, word: "Interdependenz", translation: "اِعتماد متبادل" },
    { id: 1234, word: "Autokratie", translation: "حكم مطلق" },
    { id: 1235, word: "Oligarchie", translation: "حكم الأقلية" },
    { id: 1236, word: "Plutokratie", translation: "حكم الأثرياء" },
    { id: 1237, word: "Theokratie", translation: "حكم ديني" },
    { id: 1238, word: "Anarchie", translation: "فوضى" },
    { id: 1239, word: "Totalitarismus", translation: "شمولية" },
    { id: 1240, word: "Föderalismus", translation: "فدرالية" },
    { id: 1241, word: "Zentralismus", translation: "مركزية" },
    { id: 1242, word: "Subsidiarität", translation: "مبدأ التبعية" },
    { id: 1243, word: "Kommune", translation: "بلدية / جماعة" },
    { id: 1244, word: "Metropole", translation: "عاصمة / مدينة كبرى" },
    { id: 1245, word: "Urbanisierung", translation: "تحضر / تمدين" },
    { id: 1246, word: "Demographie", translation: "علم السكان" },
    { id: 1247, word: "Kohorte", translation: "فوج / مجموعة" },
    { id: 1248, word: "Geburtenrate", translation: "معدل المواليد" },
    { id: 1249, word: "Mortalität", translation: "معدل الوفيات" },
    { id: 1250, word: "Morbidität", translation: "معدل المرض" },
    { id: 1251, word: "Inzidenz", translation: "معدل الحدوث" },
    { id: 1252, word: "Prävalenz", translation: "اِنتشار (مرض)" },
    { id: 1253, word: "Ätiologie", translation: "علم المسببات" },
    { id: 1254, word: "Phylogenese", translation: "تطور السلالات" },
    { id: 1255, word: "Ontogenese", translation: "تطور الفرد" },
    { id: 1256, word: "Adaption", translation: "تكيّف" },
    { id: 1257, word: "Selektion", translation: "اِنتقاء" },
    { id: 1258, word: "Mutation", translation: "طفرة" },
    { id: 1259, word: "Transzendental", translation: "متعالٍ / متعال (فلسفة)" },
    { id: 1260, word: "Immanent", translation: "ملازم / داخلي" },
    { id: 1261, word: "Affekt", translation: "اِنفعال / عاطفة" },
    { id: 1262, word: "Kathexis", translation: "اِستثمار ليبي (تحليل نفسي)" },
    { id: 1263, word: "Regression", translation: "تراجع" },
    { id: 1264, word: "Projektion", translation: "إسقاط (نفسي)" },
    { id: 1265, word: "Rationalisierung", translation: "عقلنة" },
    { id: 1266, word: "Verdrängung", translation: "كبت" },
    { id: 1267, word: "Introjektion", translation: "اِستدخال" },
    { id: 1268, word: "Introvertiert", translation: "اِنطوائي" },
    { id: 1269, word: "Extrovertiert", translation: "اِنبساطي" },
    { id: 1270, word: "Ambivert", translation: "متوسط بين اِنطوائي واِنبساطي" },
    { id: 1271, word: "Interpersonell", translation: "بين الأشخاص" },
    { id: 1272, word: "Intrapersonell", translation: "ضمن الشخص نفسه" },
    { id: 1273, word: "Empathisch", translation: "متعاطف" },
    { id: 1274, word: "Stoisch", translation: "رواقي" },
    { id: 1275, word: "Zynisch", translation: "ساخر / متهكم" },
    { id: 1276, word: "Sarkastisch", translation: "ساخر" },
    { id: 1277, word: "Lakonie", translation: "إيجاز" },
    { id: 1278, word: "Eloquenz", translation: "بلاغة" },
    { id: 1279, word: "Rhetorik", translation: "بلاغة / فن الخطابة" },
    { id: 1280, word: "Sophismus", translation: "مغالطة منطقية" },
    { id: 1281, word: "Dilettant", translation: "هاوٍ / غير محترف" },
    { id: 1282, word: "Virtuose", translation: "مُبدع / ماهر جداً" },
    { id: 1283, word: "Koryphäe", translation: "شخصية بارزة" },
    { id: 1284, word: "Philatelie", translation: "جمع الطوابع" },
    { id: 1285, word: "Numismatik", translation: "جمع العملات" },
    { id: 1286, word: "Paläontologie", translation: "علم الأحافير" },
    { id: 1287, word: "Kosmologie", translation: "علم الكون" },
    { id: 1288, word: "Theodizee", translation: "تبرير وجود الشر" },
    { id: 1289, word: "Exegese", translation: "تفسير نص" },
    { id: 1290, word: "Polemisch", translation: "جدلي / خلاف" },
    { id: 1291, word: "Litanei", translation: "تكرار ممل / اِبتهاج" },
    { id: 1292, word: "Apologie", translation: "دفاع / تبرير" },
    { id: 1293, word: "Hagiographie", translation: "كتابة سير القديسين (مدح مبالغ فيه)" },
    { id: 1294, word: "Ambiguität", translation: "اِبهام / غموض" },
    { id: 1295, word: "Nuance", translation: "فارق دقيق" },
    { id: 1296, word: "Feingefühl", translation: "حس مرهف / لباقة" },
    { id: 1297, word: "Diskrepanz", translation: "تضارب / اِختلاف" },
    { id: 1298, word: "Akkumulation", translation: "تراكم" },
    { id: 1299, word: "Desintegration", translation: "تفكك" },
    { id: 1300, word: "Proliferation", translation: "اِنتشار سريع" },
    { id: 1301, word: "Fusionieren", translation: "يندمج" },
    { id: 1302, word: "Akzeptabel", translation: "مقبول" },
    { id: 1303, word: "Indiskutabel", translation: "لا يمكن مناقشته" },
    { id: 1304, word: "Fakultativ", translation: "اِختياري" },
    { id: 1305, word: "Mandatorisch", translation: "اِجباري" },
    { id: 1306, word: "Transversal", translation: "عرضي / مستعرض" },
    { id: 1307, word: "Orthogonal", translation: "متعامد" },
    { id: 1308, word: "Intertextualität", translation: "تناص" },
    { id: 1309, word: "Apostasie", translation: "اِرتداد عن الدين" },
    { id: 1310, word: "Eremit", translation: "ناسك / متوحد" },
    { id: 1311, word: "Asket", translation: "زاهد" },
    { id: 1312, word: "Hedonist", translation: "باحث عن اللذة" },
    { id: 1313, word: "Stoiker", translation: "رواقي" },
    { id: 1314, word: "Zyniker", translation: "متهكم" },
    { id: 1315, word: "Skeptiker", translation: "متشكك" },
    { id: 1316, word: "Konformist", translation: "ممتثل" },
    { id: 1317, word: "Nonkonformist", translation: "غير ممتثل" },
    { id: 1318, word: "Amoralisch", translation: "غير أخلاقي" },
    { id: 1319, word: "Immoralisch", translation: "فاسد أخلاقياً" },
    { id: 1320, word: "Moralisch", translation: "أخلاقي" },
    { id: 1321, word: "Ethisch", translation: "أخلاقي (مبدئي)" },
    { id: 1322, word: "Postfaktisch", translation: "ما بعد الحقيقة" },
    { id: 1323, word: "Deutungshoheit", translation: "اِحتكار التفسير" },
    { id: 1324, word: "Chiffre", translation: "رمز / شفرة" },
    { id: 1325, word: "Exempel", translation: "مثال / عبرة" },
    { id: 1326, word: "Exzerpt", translation: "مقتطف" },
    { id: 1327, word: "Abstrahieren", translation: "يجرد" },
    { id: 1328, word: "Konkretisieren", translation: "يجعل ملموساً" },
    { id: 1329, word: "Prokrastination", translation: "تسويف / تأجيل" },
    { id: 1330, word: "Akzeleration", translation: "تسريع" },
    { id: 1331, word: "Deakzeleration", translation: "إبطاء" },
    { id: 1332, word: "Peripetie", translation: "اِنعكاس مفاجئ (قصة)" },
    { id: 1333, word: "Klimax", translation: "ذروة" },
    { id: 1334, word: "Antiklimax", translation: "تراجع بعد الذروة" },
    { id: 1335, word: "Metonymie", translation: "كناية" },
    { id: 1336, word: "Synekdoche", translation: "مجاز مرسل" },
    { id: 1337, word: "Litotes", translation: "تخفيف (بلاغة)" },
    { id: 1338, word: "Hyperbel", translation: "مبالغة" },
    { id: 1339, word: "Paradoxon", translation: "مفارقة" },
    { id: 1340, word: "Aporie", translation: "مأزق / حيرة (فلسفة)" },
    { id: 1341, word: "Kultivieren", translation: "يزرع / يثقف" },
    { id: 1342, word: "Rudimentär", translation: "بدائي" },
    { id: 1343, word: "Inherent", translation: "متأصل / جوهري" },
    { id: 1344, word: "Exteritoriale", translation: "خارج اِلإقليم" },
    { id: 1345, word: "Territorialität", translation: "إقليمية" },
    { id: 1346, word: "Exterritorialität", translation: "خارج الإقليمية" },
    { id: 1347, word: "Autokratisch", translation: "اِستبدادي" },
    { id: 1348, word: "Plebiszit", translation: "اِستفتاء شعبي" },
    { id: 1349, word: "Postulieren", translation: "يفترض / يطالب" },
    { id: 1350, word: "Exklusion", translation: "اِستثناء / إقصاء" },
    { id: 1351, word: "Inklusion", translation: "اِشتمال" },
    { id: 1352, word: "Disparität", translation: "تفاوت / عدم مساواة" },
    { id: 1353, word: "Egalität", translation: "مساواة" },
    { id: 1354, word: "Homogen", translation: "متجانس" },
    { id: 1355, word: "Heterogen", translation: "غير متجانس" },
    { id: 1356, word: "Agnostizismus", translation: "لاأدرية" },
    { id: 1357, word: "Theismus", translation: "توحيد" },
    { id: 1358, word: "Atheismus", translation: "إلحاد" },
    { id: 1359, word: "Pantheismus", translation: "وحدة الوجود" },
    { id: 1360, word: "Deismus", translation: "ربوبية" },
    { id: 1361, word: "Monotheismus", translation: "توحيد (اِلإيمان بإله واحد)" },
    { id: 1362, word: "Polytheismus", translation: "تعدد الآلهة" },
    { id: 1363, word: "Animismus", translation: "اِلإيمان بالأرواح" },
    { id: 1364, word: "Fabulieren", translation: "يخترع قصصاً" },
    { id: 1365, word: "Spekulativ", translation: "تخميني" },
    { id: 1366, word: "Kalkül", translation: "حساب / تدبير" },
    { id: 1367, word: "Konfektionieren", translation: "يُجهز / يُعبئ" },
    { id: 1368, word: "Indizieren", translation: "يشير إلى / يفهرس" },
    { id: 1369, word: "Manifestieren", translation: "يُظهر / يتجلى" },
    { id: 1370, word: "Okkult", translation: "خفي / سري" },
    { id: 1371, word: "Esoterisch", translation: "باطني" },
    { id: 1372, word: "Exoterisch", translation: "ظاهري" },
    { id: 1373, word: "Akustisch", translation: "صوتي" },
    { id: 1374, word: "Optisch", translation: "بصري" },
    { id: 1375, word: "Sensorisch", translation: "حسي" },
    { id: 1376, word: "Motorisch", translation: "حركي" },
    { id: 1377, word: "Kognitiv", translation: "معرفي" },
    { id: 1378, word: "Affektiv", translation: "عاطفي" },
    { id: 1379, word: "Psychomotorisch", translation: "نفسي حركي" },
    { id: 1380, word: "Didaktik", translation: "علم التدريس" },
    { id: 1381, word: "Pädagogik", translation: "تربية" },
    { id: 1382, word: "Curriculum", translation: "منهج دراسي" },
    { id: 1383, word: "Modul", translation: "وحدة (دراسة)" },
    { id: 1384, word: "Habilitation", translation: "أعلى درجة أكاديمية في ألمانيا" },
    { id: 1385, word: "Emeritus", translation: "أستاذ فخري متقاعد" },
    { id: 1386, word: "Postdoc", translation: "باحث ما بعد الدكتوراه" },
    { id: 1387, word: "Stipendium", translation: "منحة دراسية" },
    { id: 1388, word: "Dissertation", translation: "أطروحة دكتوراه" },
    { id: 1389, word: "Monographie", translation: "دراسة شاملة لموضوع واحد" },
    { id: 1390, word: "Anthologie", translation: "مجموعة مختارات أدبية" },
    { id: 1391, word: "Exkurs", translation: "اِستطراد" },
    { id: 1392, word: "Exzerpieren", translation: "يلخص / يقتطف" },
    { id: 1393, word: "Konkludent", translation: "اِستنتاجي / ضمني" },
    { id: 1394, word: "Per definitionem", translation: "بحكم التعريف" },
    { id: 1395, word: "Akkreditieren", translation: "يعتمد" },
    { id: 1396, word: "Desavouieren", translation: "يتنكر لـ" },
    { id: 1397, word: "Dezidiert", translation: "مُصمم / حاسم" },
    { id: 1398, word: "Entfremdung", translation: "اِغتراب" },
    { id: 1399, word: "Kontemplation", translation: "تأمل" },
    { id: 1400, word: "Pathos", translation: "حماس / عاطفة" },
    { id: 1401, word: "Ethos", translation: "روح / خلق" },
    { id: 1402, word: "Logos", translation: "منطق / عقل" },
    { id: 1403, word: "Kryptisch", translation: "مبهم / غامض" },
    { id: 1404, word: "Versiert", translation: "ماهر / خبير" },
    { id: 1405, word: "Ressentiment", translation: "حقد" },
    { id: 1406, word: "Indigen", translation: "أصلي / محلي" },
    { id: 1407, word: "Diaspora", translation: "شتات" },
    { id: 1408, word: "Plädoyer", translation: "مرافعة" },
    { id: 1409, word: "Pönitent", translation: "تائب" },
    { id: 1410, word: "Säkular", translation: "دنيوي / علماني" },
    { id: 1411, word: "Aszese", translation: "زهد" },
    { id: 1412, word: "Kontinuum", translation: "اِستمرارية" },
    { id: 1413, word: "Diskret", translation: "مُنفصل / سري" },
    { id: 1414, word: "Disparität", translation: "تفاوت" },
    { id: 1415, word: "Austerität", translation: "تقشف" },
    { id: 1416, word: "Substantiieren", translation: "يُثبت / يُجسّد" },
    { id: 1417, word: "Redundanz", translation: "تكرار غير ضروري" },
    { id: 1418, word: "Epitaph", translation: "نقش على ضريح" },
    { id: 1419, word: "Haplologie", translation: "حذف مقطع صوتي (لغويات)" },
    { id: 1420, word: "Kompendium", translation: "مختصر / موجز" },
    { id: 1421, word: "Divergent", translation: "مختلف / متباعد" },
    { id: 1422, word: "Konvergent", translation: "متقارب" },
    { id: 1423, word: "Antagonismus", translation: "تناحر" },
    { id: 1424, word: "Antagonist", translation: "خصم" },
    { id: 1425, word: "Protagonist", translation: "بطل (قصة)" },
    { id: 1426, word: "Dramaturgie", translation: "فن المسرح" },
    { id: 1427, word: "Äquidistanz", translation: "تساوي المسافة" },
    { id: 1428, word: "Konkomitierend", translation: "مصاحب" },
    { id: 1429, word: "Korrespondierend", translation: "متوافق" },
    { id: 1430, word: "Diskrepanz", translation: "تضارب" },
    { id: 1431, word: "Intransigent", translation: "متعنت" },
    { id: 1432, word: "Akzessorisch", translation: "اِضافي / ثانوي" },
    { id: 1433, word: "Fundament", translation: "أساس" },
    { id: 1434, word: "Essenz", translation: "جوهر" },
    { id: 1435, word: "Peripherie", translation: "محيط / أطراف" },
    { id: 1436, word: "Singularität", translation: "تفرد" },
    { id: 1437, word: "Pluralität", translation: "تعددية" },
    { id: 1438, word: "Ambition", translation: "طموح" },
    { id: 1439, word: "Ehrgeiz", translation: "طموح" },
    { id: 1440, word: "Aspiration", translation: "طموح / تطلع" },
    { id: 1441, word: "Ambitioniert", translation: "طموح" },
    { id: 1442, word: "Versiertheit", translation: "براعة / خبرة" },
    { id: 1443, word: "Impertinent", translation: "وقح / غير ذي صلة" },
    { id: 1444, word: "Pertinent", translation: "ذي صلة" },
    { id: 1445, word: "Definitorisch", translation: "تعريفي" },
    { id: 1446, word: "Interdisziplinär", translation: "متعدد التخصصات" },
    { id: 1447, word: "Transdisziplinär", translation: "عبر التخصصات" },
    { id: 1448, word: "Holistisch", translation: "شمولي" },
    { id: 1449, word: "Segmentieren", translation: "يُجزئ / يقسم" },
    { id: 1450, word: "Integrativ", translation: "تكاملي" },
    { id: 1451, word: "Synkopieren", translation: "يختصر (موسيقى/لغة)" },
    { id: 1452, word: "Asymmetrie", translation: "لا تماثل" },
    { id: 1453, word: "Symmetrie", translation: "تماثل" },
    { id: 1454, word: "Konklusion", translation: "اِستنتاج" },
    { id: 1455, word: "Duktus", translation: "أسلوب / طريقة" },
    { id: 1456, word: "Lexikon", translation: "معجم" },
    { id: 1457, word: "Pondera", translation: "أثقال / توازنات" },
    { id: 1458, word: "Aspekt", translation: "جانب" },
    { id: 1459, word: "Spektrum", translation: "طيف" },
    { id: 1460, word: "Ära", translation: "حقبة" },
    { id: 1461, word: "Dekade", translation: "عقد (عشر سنوات)" },
    { id: 1462, word: "Millennium", translation: "ألفية" },
    { id: 1463, word: "Ewigkeit", translation: "أبدية" },
    { id: 1464, word: "Kontinuierlich", translation: "مستمر" },
    { id: 1465, word: "Diskret", translation: "متقطع / منفصل" },
    { id: 1466, word: "Ad hoc", translation: "لهذا الغرض تحديداً" },
    { id: 1467, word: "A priori", translation: "قبلي / بالمنطق" },
    { id: 1468, word: "Ex officio", translation: "بحكم منصبه" },
    { id: 1469, word: "Per se", translation: "في حد ذاته" },
    { id: 1470, word: "Vizinal", translation: "مُجاور" },
    { id: 1471, word: "Labil", translation: "غير مستقر" },
    { id: 1472, word: "Stabil", translation: "مستقر" },
    { id: 1473, word: "Fragilität", translation: "هشاشة" },
    { id: 1474, word: "Robustheit", translation: "متانة" },
    { id: 1475, word: "Konkludent", translation: "اِستنتاجي" },
    { id: 1476, word: "Konsolidierung", translation: "توحيد / تعزيز" },
    { id: 1477, word: "Subsumption", translation: "تصنيف تحت قاعدة" },
    { id: 1478, word: "Vag", translation: "غامض / مبهم" },
    { id: 1479, word: "Präzise", translation: "دقيق" },
    { id: 1480, word: "Subtil", translation: "دقيق / خفي" },
    { id: 1481, word: "Eklat", translation: "فضيحة / مشهد صاخب" },
    { id: 1482, word: "Prokrastinieren", translation: "يسوف / يؤجل" },
    { id: 1483, word: "Evident", translation: "واضح / بيّن" },
    { id: 1484, word: "Okkasion", translation: "مناسبة" },
    { id: 1485, word: "Agnostisch", translation: "لا أدري" },
    { id: 1486, word: "Teleologie", translation: "علم الغائية" },
    { id: 1487, word: "Ontologisch", translation: "وجودي" },
    { id: 1488, word: "Akronym", translation: "اِختصار" },
    { id: 1489, word: "Homonym", translation: "كلمة متماثلة اللفظ مختلفة المعنى" },
    { id: 1490, word: "Homophon", translation: "كلمة متماثلة الصوت مختلفة الكتابة" },
    { id: 1491, word: "Synästhesie", translation: "اِختلاط الحواس" },
    { id: 1492, word: "Diachron", translation: "تاريخي (لغويات)" },
    { id: 1493, word: "Synchron", translation: "متزامن" },
    { id: 1494, word: "Dekomponieren", translation: "يُفكك" },
    { id: 1495, word: "Konstituieren", translation: "يُشكل / يُنشئ" },
    { id: 1496, word: "Eklektizismus", translation: "اِنتقائية" },
    { id: 1497, word: "Impetus", translation: "قوة دافعة" },
    { id: 1498, word: "Prädestination", translation: "قضاء وقدر" },
    { id: 1499, word: "Antizipation", translation: "اِستباق" },
    { id: 1500, word: "Simultan", translation: "متزامن" }
  ]
}

export default germanWords;
